// Generated by `yarn new:queryMock`
import { server } from '../../server';
import { projectTaskQuery } from '../project-task';
import type { Options } from './type';

export const setProjectTaskQuery = (options: Options) => {
  server.use(projectTaskQuery(options));
};
