packages:
  - apps/*
  - packages/**

catalog:
  react-native: 0.86.2
  react: 19.2.3
  react-dom: 19.2.3

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  esbuild: true
  lefthook: true
  msw: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@react-native-rethemed/chakra-ui-tokens@0.1.1'
  - '@react-native-rethemed/cli@0.1.1'
  - '@react-native-rethemed/core@0.1.1'
  - '@react-native-rethemed/material-design-tokens@0.1.1'
