// Code generated by ent, DO NOT EDIT.

package tasklistcompletedstatus

import (
	"fmt"
	"io"
	"project-management-demo-backend/ent/schema/ulid"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tasklistcompletedstatus type in the database.
	Label = "task_list_completed_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTeammateTaskListStatuses holds the string denoting the teammatetaskliststatuses edge name in mutations.
	EdgeTeammateTaskListStatuses = "teammateTaskListStatuses"
	// EdgeProjectTaskListStatuses holds the string denoting the projecttaskliststatuses edge name in mutations.
	EdgeProjectTaskListStatuses = "projectTaskListStatuses"
	// Table holds the table name of the tasklistcompletedstatus in the database.
	Table = "task_list_completed_status"
	// TeammateTaskListStatusesTable is the table that holds the teammateTaskListStatuses relation/edge.
	TeammateTaskListStatusesTable = "teammate_task_list_status"
	// TeammateTaskListStatusesInverseTable is the table name for the TeammateTaskListStatus entity.
	// It exists in this package in order to avoid circular dependency with the "teammatetaskliststatus" package.
	TeammateTaskListStatusesInverseTable = "teammate_task_list_status"
	// TeammateTaskListStatusesColumn is the table column denoting the teammateTaskListStatuses relation/edge.
	TeammateTaskListStatusesColumn = "task_list_completed_status_id"
	// ProjectTaskListStatusesTable is the table that holds the projectTaskListStatuses relation/edge.
	ProjectTaskListStatusesTable = "project_task_list_status"
	// ProjectTaskListStatusesInverseTable is the table name for the ProjectTaskListStatus entity.
	// It exists in this package in order to avoid circular dependency with the "projecttaskliststatus" package.
	ProjectTaskListStatusesInverseTable = "project_task_list_status"
	// ProjectTaskListStatusesColumn is the table column denoting the projectTaskListStatuses relation/edge.
	ProjectTaskListStatusesColumn = "task_list_completed_status_id"
)

// Columns holds all SQL columns for tasklistcompletedstatus fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStatusCode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)

// StatusCode defines the type for the "status_code" enum field.
type StatusCode string

// StatusCode values.
const (
	StatusCodeIncomplete         StatusCode = "INCOMPLETE"
	StatusCodeCompleted          StatusCode = "COMPLETED"
	StatusCodeCompletedToday     StatusCode = "COMPLETED_TODAY"
	StatusCodeCompletedYesterday StatusCode = "COMPLETED_YESTERDAY"
	StatusCodeCompleted1Week     StatusCode = "COMPLETED_1_WEEK"
	StatusCodeCompleted2Weeks    StatusCode = "COMPLETED_2_WEEKS"
	StatusCodeCompleted3Weeks    StatusCode = "COMPLETED_3_WEEKS"
	StatusCodeAll                StatusCode = "ALL"
)

func (sc StatusCode) String() string {
	return string(sc)
}

// StatusCodeValidator is a validator for the "status_code" field enum values. It is called by the builders before save.
func StatusCodeValidator(sc StatusCode) error {
	switch sc {
	case StatusCodeIncomplete, StatusCodeCompleted, StatusCodeCompletedToday, StatusCodeCompletedYesterday, StatusCodeCompleted1Week, StatusCodeCompleted2Weeks, StatusCodeCompleted3Weeks, StatusCodeAll:
		return nil
	default:
		return fmt.Errorf("tasklistcompletedstatus: invalid enum value for status_code field: %q", sc)
	}
}

// OrderOption defines the ordering options for the TaskListCompletedStatus queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeammateTaskListStatusesCount orders the results by teammateTaskListStatuses count.
func ByTeammateTaskListStatusesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeammateTaskListStatusesStep(), opts...)
	}
}

// ByTeammateTaskListStatuses orders the results by teammateTaskListStatuses terms.
func ByTeammateTaskListStatuses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeammateTaskListStatusesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectTaskListStatusesCount orders the results by projectTaskListStatuses count.
func ByProjectTaskListStatusesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectTaskListStatusesStep(), opts...)
	}
}

// ByProjectTaskListStatuses orders the results by projectTaskListStatuses terms.
func ByProjectTaskListStatuses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectTaskListStatusesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTeammateTaskListStatusesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeammateTaskListStatusesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeammateTaskListStatusesTable, TeammateTaskListStatusesColumn),
	)
}
func newProjectTaskListStatusesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectTaskListStatusesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectTaskListStatusesTable, ProjectTaskListStatusesColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e StatusCode) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *StatusCode) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = StatusCode(str)
	if err := StatusCodeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid StatusCode", str)
	}
	return nil
}
