// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/activitytype"
	"project-management-demo-backend/ent/archivedtaskactivity"
	"project-management-demo-backend/ent/archivedworkspaceactivity"
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/taskactivity"
	"project-management-demo-backend/ent/workspaceactivity"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActivityTypeUpdate is the builder for updating ActivityType entities.
type ActivityTypeUpdate struct {
	config
	hooks    []Hook
	mutation *ActivityTypeMutation
}

// Where appends a list predicates to the ActivityTypeUpdate builder.
func (_u *ActivityTypeUpdate) Where(ps ...predicate.ActivityType) *ActivityTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ActivityTypeUpdate) SetName(v string) *ActivityTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActivityTypeUpdate) SetNillableName(v *string) *ActivityTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTypeCode sets the "type_code" field.
func (_u *ActivityTypeUpdate) SetTypeCode(v activitytype.TypeCode) *ActivityTypeUpdate {
	_u.mutation.SetTypeCode(v)
	return _u
}

// SetNillableTypeCode sets the "type_code" field if the given value is not nil.
func (_u *ActivityTypeUpdate) SetNillableTypeCode(v *activitytype.TypeCode) *ActivityTypeUpdate {
	if v != nil {
		_u.SetTypeCode(*v)
	}
	return _u
}

// AddTaskActivityIDs adds the "taskActivities" edge to the TaskActivity entity by IDs.
func (_u *ActivityTypeUpdate) AddTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.AddTaskActivityIDs(ids...)
	return _u
}

// AddTaskActivities adds the "taskActivities" edges to the TaskActivity entity.
func (_u *ActivityTypeUpdate) AddTaskActivities(v ...*TaskActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskActivityIDs(ids...)
}

// AddWorkspaceActivityIDs adds the "workspaceActivities" edge to the WorkspaceActivity entity by IDs.
func (_u *ActivityTypeUpdate) AddWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.AddWorkspaceActivityIDs(ids...)
	return _u
}

// AddWorkspaceActivities adds the "workspaceActivities" edges to the WorkspaceActivity entity.
func (_u *ActivityTypeUpdate) AddWorkspaceActivities(v ...*WorkspaceActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkspaceActivityIDs(ids...)
}

// AddArchivedTaskActivityIDs adds the "archivedTaskActivities" edge to the ArchivedTaskActivity entity by IDs.
func (_u *ActivityTypeUpdate) AddArchivedTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.AddArchivedTaskActivityIDs(ids...)
	return _u
}

// AddArchivedTaskActivities adds the "archivedTaskActivities" edges to the ArchivedTaskActivity entity.
func (_u *ActivityTypeUpdate) AddArchivedTaskActivities(v ...*ArchivedTaskActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchivedTaskActivityIDs(ids...)
}

// AddArchivedWorkspaceActivityIDs adds the "archivedWorkspaceActivities" edge to the ArchivedWorkspaceActivity entity by IDs.
func (_u *ActivityTypeUpdate) AddArchivedWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.AddArchivedWorkspaceActivityIDs(ids...)
	return _u
}

// AddArchivedWorkspaceActivities adds the "archivedWorkspaceActivities" edges to the ArchivedWorkspaceActivity entity.
func (_u *ActivityTypeUpdate) AddArchivedWorkspaceActivities(v ...*ArchivedWorkspaceActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchivedWorkspaceActivityIDs(ids...)
}

// Mutation returns the ActivityTypeMutation object of the builder.
func (_u *ActivityTypeUpdate) Mutation() *ActivityTypeMutation {
	return _u.mutation
}

// ClearTaskActivities clears all "taskActivities" edges to the TaskActivity entity.
func (_u *ActivityTypeUpdate) ClearTaskActivities() *ActivityTypeUpdate {
	_u.mutation.ClearTaskActivities()
	return _u
}

// RemoveTaskActivityIDs removes the "taskActivities" edge to TaskActivity entities by IDs.
func (_u *ActivityTypeUpdate) RemoveTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.RemoveTaskActivityIDs(ids...)
	return _u
}

// RemoveTaskActivities removes "taskActivities" edges to TaskActivity entities.
func (_u *ActivityTypeUpdate) RemoveTaskActivities(v ...*TaskActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskActivityIDs(ids...)
}

// ClearWorkspaceActivities clears all "workspaceActivities" edges to the WorkspaceActivity entity.
func (_u *ActivityTypeUpdate) ClearWorkspaceActivities() *ActivityTypeUpdate {
	_u.mutation.ClearWorkspaceActivities()
	return _u
}

// RemoveWorkspaceActivityIDs removes the "workspaceActivities" edge to WorkspaceActivity entities by IDs.
func (_u *ActivityTypeUpdate) RemoveWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.RemoveWorkspaceActivityIDs(ids...)
	return _u
}

// RemoveWorkspaceActivities removes "workspaceActivities" edges to WorkspaceActivity entities.
func (_u *ActivityTypeUpdate) RemoveWorkspaceActivities(v ...*WorkspaceActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkspaceActivityIDs(ids...)
}

// ClearArchivedTaskActivities clears all "archivedTaskActivities" edges to the ArchivedTaskActivity entity.
func (_u *ActivityTypeUpdate) ClearArchivedTaskActivities() *ActivityTypeUpdate {
	_u.mutation.ClearArchivedTaskActivities()
	return _u
}

// RemoveArchivedTaskActivityIDs removes the "archivedTaskActivities" edge to ArchivedTaskActivity entities by IDs.
func (_u *ActivityTypeUpdate) RemoveArchivedTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.RemoveArchivedTaskActivityIDs(ids...)
	return _u
}

// RemoveArchivedTaskActivities removes "archivedTaskActivities" edges to ArchivedTaskActivity entities.
func (_u *ActivityTypeUpdate) RemoveArchivedTaskActivities(v ...*ArchivedTaskActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchivedTaskActivityIDs(ids...)
}

// ClearArchivedWorkspaceActivities clears all "archivedWorkspaceActivities" edges to the ArchivedWorkspaceActivity entity.
func (_u *ActivityTypeUpdate) ClearArchivedWorkspaceActivities() *ActivityTypeUpdate {
	_u.mutation.ClearArchivedWorkspaceActivities()
	return _u
}

// RemoveArchivedWorkspaceActivityIDs removes the "archivedWorkspaceActivities" edge to ArchivedWorkspaceActivity entities by IDs.
func (_u *ActivityTypeUpdate) RemoveArchivedWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdate {
	_u.mutation.RemoveArchivedWorkspaceActivityIDs(ids...)
	return _u
}

// RemoveArchivedWorkspaceActivities removes "archivedWorkspaceActivities" edges to ArchivedWorkspaceActivity entities.
func (_u *ActivityTypeUpdate) RemoveArchivedWorkspaceActivities(v ...*ArchivedWorkspaceActivity) *ActivityTypeUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchivedWorkspaceActivityIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivityTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivityTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := activitytype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ActivityType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypeCode(); ok {
		if err := activitytype.TypeCodeValidator(v); err != nil {
			return &ValidationError{Name: "type_code", err: fmt.Errorf(`ent: validator failed for field "ActivityType.type_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivityTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activitytype.Table, activitytype.Columns, sqlgraph.NewFieldSpec(activitytype.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(activitytype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TypeCode(); ok {
		_spec.SetField(activitytype.FieldTypeCode, field.TypeEnum, value)
	}
	if _u.mutation.TaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.TaskActivitiesTable,
			Columns: []string{activitytype.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskActivitiesIDs(); len(nodes) > 0 && !_u.mutation.TaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.TaskActivitiesTable,
			Columns: []string{activitytype.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.TaskActivitiesTable,
			Columns: []string{activitytype.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.WorkspaceActivitiesTable,
			Columns: []string{activitytype.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkspaceActivitiesIDs(); len(nodes) > 0 && !_u.mutation.WorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.WorkspaceActivitiesTable,
			Columns: []string{activitytype.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.WorkspaceActivitiesTable,
			Columns: []string{activitytype.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArchivedTaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedTaskActivitiesTable,
			Columns: []string{activitytype.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivedTaskActivitiesIDs(); len(nodes) > 0 && !_u.mutation.ArchivedTaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedTaskActivitiesTable,
			Columns: []string{activitytype.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivedTaskActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedTaskActivitiesTable,
			Columns: []string{activitytype.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArchivedWorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedWorkspaceActivitiesTable,
			Columns: []string{activitytype.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivedWorkspaceActivitiesIDs(); len(nodes) > 0 && !_u.mutation.ArchivedWorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedWorkspaceActivitiesTable,
			Columns: []string{activitytype.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivedWorkspaceActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedWorkspaceActivitiesTable,
			Columns: []string{activitytype.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activitytype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivityTypeUpdateOne is the builder for updating a single ActivityType entity.
type ActivityTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivityTypeMutation
}

// SetName sets the "name" field.
func (_u *ActivityTypeUpdateOne) SetName(v string) *ActivityTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActivityTypeUpdateOne) SetNillableName(v *string) *ActivityTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTypeCode sets the "type_code" field.
func (_u *ActivityTypeUpdateOne) SetTypeCode(v activitytype.TypeCode) *ActivityTypeUpdateOne {
	_u.mutation.SetTypeCode(v)
	return _u
}

// SetNillableTypeCode sets the "type_code" field if the given value is not nil.
func (_u *ActivityTypeUpdateOne) SetNillableTypeCode(v *activitytype.TypeCode) *ActivityTypeUpdateOne {
	if v != nil {
		_u.SetTypeCode(*v)
	}
	return _u
}

// AddTaskActivityIDs adds the "taskActivities" edge to the TaskActivity entity by IDs.
func (_u *ActivityTypeUpdateOne) AddTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.AddTaskActivityIDs(ids...)
	return _u
}

// AddTaskActivities adds the "taskActivities" edges to the TaskActivity entity.
func (_u *ActivityTypeUpdateOne) AddTaskActivities(v ...*TaskActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskActivityIDs(ids...)
}

// AddWorkspaceActivityIDs adds the "workspaceActivities" edge to the WorkspaceActivity entity by IDs.
func (_u *ActivityTypeUpdateOne) AddWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.AddWorkspaceActivityIDs(ids...)
	return _u
}

// AddWorkspaceActivities adds the "workspaceActivities" edges to the WorkspaceActivity entity.
func (_u *ActivityTypeUpdateOne) AddWorkspaceActivities(v ...*WorkspaceActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkspaceActivityIDs(ids...)
}

// AddArchivedTaskActivityIDs adds the "archivedTaskActivities" edge to the ArchivedTaskActivity entity by IDs.
func (_u *ActivityTypeUpdateOne) AddArchivedTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.AddArchivedTaskActivityIDs(ids...)
	return _u
}

// AddArchivedTaskActivities adds the "archivedTaskActivities" edges to the ArchivedTaskActivity entity.
func (_u *ActivityTypeUpdateOne) AddArchivedTaskActivities(v ...*ArchivedTaskActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchivedTaskActivityIDs(ids...)
}

// AddArchivedWorkspaceActivityIDs adds the "archivedWorkspaceActivities" edge to the ArchivedWorkspaceActivity entity by IDs.
func (_u *ActivityTypeUpdateOne) AddArchivedWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.AddArchivedWorkspaceActivityIDs(ids...)
	return _u
}

// AddArchivedWorkspaceActivities adds the "archivedWorkspaceActivities" edges to the ArchivedWorkspaceActivity entity.
func (_u *ActivityTypeUpdateOne) AddArchivedWorkspaceActivities(v ...*ArchivedWorkspaceActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchivedWorkspaceActivityIDs(ids...)
}

// Mutation returns the ActivityTypeMutation object of the builder.
func (_u *ActivityTypeUpdateOne) Mutation() *ActivityTypeMutation {
	return _u.mutation
}

// ClearTaskActivities clears all "taskActivities" edges to the TaskActivity entity.
func (_u *ActivityTypeUpdateOne) ClearTaskActivities() *ActivityTypeUpdateOne {
	_u.mutation.ClearTaskActivities()
	return _u
}

// RemoveTaskActivityIDs removes the "taskActivities" edge to TaskActivity entities by IDs.
func (_u *ActivityTypeUpdateOne) RemoveTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.RemoveTaskActivityIDs(ids...)
	return _u
}

// RemoveTaskActivities removes "taskActivities" edges to TaskActivity entities.
func (_u *ActivityTypeUpdateOne) RemoveTaskActivities(v ...*TaskActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskActivityIDs(ids...)
}

// ClearWorkspaceActivities clears all "workspaceActivities" edges to the WorkspaceActivity entity.
func (_u *ActivityTypeUpdateOne) ClearWorkspaceActivities() *ActivityTypeUpdateOne {
	_u.mutation.ClearWorkspaceActivities()
	return _u
}

// RemoveWorkspaceActivityIDs removes the "workspaceActivities" edge to WorkspaceActivity entities by IDs.
func (_u *ActivityTypeUpdateOne) RemoveWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.RemoveWorkspaceActivityIDs(ids...)
	return _u
}

// RemoveWorkspaceActivities removes "workspaceActivities" edges to WorkspaceActivity entities.
func (_u *ActivityTypeUpdateOne) RemoveWorkspaceActivities(v ...*WorkspaceActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkspaceActivityIDs(ids...)
}

// ClearArchivedTaskActivities clears all "archivedTaskActivities" edges to the ArchivedTaskActivity entity.
func (_u *ActivityTypeUpdateOne) ClearArchivedTaskActivities() *ActivityTypeUpdateOne {
	_u.mutation.ClearArchivedTaskActivities()
	return _u
}

// RemoveArchivedTaskActivityIDs removes the "archivedTaskActivities" edge to ArchivedTaskActivity entities by IDs.
func (_u *ActivityTypeUpdateOne) RemoveArchivedTaskActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.RemoveArchivedTaskActivityIDs(ids...)
	return _u
}

// RemoveArchivedTaskActivities removes "archivedTaskActivities" edges to ArchivedTaskActivity entities.
func (_u *ActivityTypeUpdateOne) RemoveArchivedTaskActivities(v ...*ArchivedTaskActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchivedTaskActivityIDs(ids...)
}

// ClearArchivedWorkspaceActivities clears all "archivedWorkspaceActivities" edges to the ArchivedWorkspaceActivity entity.
func (_u *ActivityTypeUpdateOne) ClearArchivedWorkspaceActivities() *ActivityTypeUpdateOne {
	_u.mutation.ClearArchivedWorkspaceActivities()
	return _u
}

// RemoveArchivedWorkspaceActivityIDs removes the "archivedWorkspaceActivities" edge to ArchivedWorkspaceActivity entities by IDs.
func (_u *ActivityTypeUpdateOne) RemoveArchivedWorkspaceActivityIDs(ids ...ulid.ID) *ActivityTypeUpdateOne {
	_u.mutation.RemoveArchivedWorkspaceActivityIDs(ids...)
	return _u
}

// RemoveArchivedWorkspaceActivities removes "archivedWorkspaceActivities" edges to ArchivedWorkspaceActivity entities.
func (_u *ActivityTypeUpdateOne) RemoveArchivedWorkspaceActivities(v ...*ArchivedWorkspaceActivity) *ActivityTypeUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchivedWorkspaceActivityIDs(ids...)
}

// Where appends a list predicates to the ActivityTypeUpdate builder.
func (_u *ActivityTypeUpdateOne) Where(ps ...predicate.ActivityType) *ActivityTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivityTypeUpdateOne) Select(field string, fields ...string) *ActivityTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActivityType entity.
func (_u *ActivityTypeUpdateOne) Save(ctx context.Context) (*ActivityType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityTypeUpdateOne) SaveX(ctx context.Context) *ActivityType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivityTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := activitytype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ActivityType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypeCode(); ok {
		if err := activitytype.TypeCodeValidator(v); err != nil {
			return &ValidationError{Name: "type_code", err: fmt.Errorf(`ent: validator failed for field "ActivityType.type_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivityTypeUpdateOne) sqlSave(ctx context.Context) (_node *ActivityType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activitytype.Table, activitytype.Columns, sqlgraph.NewFieldSpec(activitytype.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActivityType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activitytype.FieldID)
		for _, f := range fields {
			if !activitytype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activitytype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(activitytype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TypeCode(); ok {
		_spec.SetField(activitytype.FieldTypeCode, field.TypeEnum, value)
	}
	if _u.mutation.TaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.TaskActivitiesTable,
			Columns: []string{activitytype.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskActivitiesIDs(); len(nodes) > 0 && !_u.mutation.TaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.TaskActivitiesTable,
			Columns: []string{activitytype.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.TaskActivitiesTable,
			Columns: []string{activitytype.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.WorkspaceActivitiesTable,
			Columns: []string{activitytype.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkspaceActivitiesIDs(); len(nodes) > 0 && !_u.mutation.WorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.WorkspaceActivitiesTable,
			Columns: []string{activitytype.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.WorkspaceActivitiesTable,
			Columns: []string{activitytype.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArchivedTaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedTaskActivitiesTable,
			Columns: []string{activitytype.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivedTaskActivitiesIDs(); len(nodes) > 0 && !_u.mutation.ArchivedTaskActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedTaskActivitiesTable,
			Columns: []string{activitytype.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivedTaskActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedTaskActivitiesTable,
			Columns: []string{activitytype.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArchivedWorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedWorkspaceActivitiesTable,
			Columns: []string{activitytype.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivedWorkspaceActivitiesIDs(); len(nodes) > 0 && !_u.mutation.ArchivedWorkspaceActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedWorkspaceActivitiesTable,
			Columns: []string{activitytype.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivedWorkspaceActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitytype.ArchivedWorkspaceActivitiesTable,
			Columns: []string{activitytype.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActivityType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activitytype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
