// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/deletedworkspaceactivitytask"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/ent/task"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeletedWorkspaceActivityTaskCreate is the builder for creating a DeletedWorkspaceActivityTask entity.
type DeletedWorkspaceActivityTaskCreate struct {
	config
	mutation *DeletedWorkspaceActivityTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWorkspaceActivityID sets the "workspace_activity_id" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetWorkspaceActivityID(v ulid.ID) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetWorkspaceActivityID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetWorkspaceActivityTaskID sets the "workspace_activity_task_id" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetWorkspaceActivityTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetWorkspaceActivityTaskID(v)
	return _c
}

// SetWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetWorkspaceActivityTaskCreatedAt(v time.Time) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetWorkspaceActivityTaskCreatedAt(v)
	return _c
}

// SetWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetWorkspaceActivityTaskUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetWorkspaceActivityTaskUpdatedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetCreatedAt(v time.Time) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeletedWorkspaceActivityTaskCreate) SetNillableCreatedAt(v *time.Time) *DeletedWorkspaceActivityTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeletedWorkspaceActivityTaskCreate) SetNillableUpdatedAt(v *time.Time) *DeletedWorkspaceActivityTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeletedWorkspaceActivityTaskCreate) SetID(v ulid.ID) *DeletedWorkspaceActivityTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeletedWorkspaceActivityTaskCreate) SetNillableID(v *ulid.ID) *DeletedWorkspaceActivityTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *DeletedWorkspaceActivityTaskCreate) SetTask(v *Task) *DeletedWorkspaceActivityTaskCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the DeletedWorkspaceActivityTaskMutation object of the builder.
func (_c *DeletedWorkspaceActivityTaskCreate) Mutation() *DeletedWorkspaceActivityTaskMutation {
	return _c.mutation
}

// Save creates the DeletedWorkspaceActivityTask in the database.
func (_c *DeletedWorkspaceActivityTaskCreate) Save(ctx context.Context) (*DeletedWorkspaceActivityTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeletedWorkspaceActivityTaskCreate) SaveX(ctx context.Context) *DeletedWorkspaceActivityTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeletedWorkspaceActivityTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeletedWorkspaceActivityTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeletedWorkspaceActivityTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deletedworkspaceactivitytask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := deletedworkspaceactivitytask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := deletedworkspaceactivitytask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeletedWorkspaceActivityTaskCreate) check() error {
	if _, ok := _c.mutation.WorkspaceActivityID(); !ok {
		return &ValidationError{Name: "workspace_activity_id", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.workspace_activity_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.task_id"`)}
	}
	if _, ok := _c.mutation.WorkspaceActivityTaskID(); !ok {
		return &ValidationError{Name: "workspace_activity_task_id", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.workspace_activity_task_id"`)}
	}
	if _, ok := _c.mutation.WorkspaceActivityTaskCreatedAt(); !ok {
		return &ValidationError{Name: "workspace_activity_task_created_at", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.workspace_activity_task_created_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceActivityTaskUpdatedAt(); !ok {
		return &ValidationError{Name: "workspace_activity_task_updated_at", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.workspace_activity_task_updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeletedWorkspaceActivityTask.updated_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "DeletedWorkspaceActivityTask.task"`)}
	}
	return nil
}

func (_c *DeletedWorkspaceActivityTaskCreate) sqlSave(ctx context.Context) (*DeletedWorkspaceActivityTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeletedWorkspaceActivityTaskCreate) createSpec() (*DeletedWorkspaceActivityTask, *sqlgraph.CreateSpec) {
	var (
		_node = &DeletedWorkspaceActivityTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deletedworkspaceactivitytask.Table, sqlgraph.NewFieldSpec(deletedworkspaceactivitytask.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.WorkspaceActivityID(); ok {
		_spec.SetField(deletedworkspaceactivitytask.FieldWorkspaceActivityID, field.TypeString, value)
		_node.WorkspaceActivityID = value
	}
	if value, ok := _c.mutation.WorkspaceActivityTaskID(); ok {
		_spec.SetField(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskID, field.TypeString, value)
		_node.WorkspaceActivityTaskID = value
	}
	if value, ok := _c.mutation.WorkspaceActivityTaskCreatedAt(); ok {
		_spec.SetField(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskCreatedAt, field.TypeTime, value)
		_node.WorkspaceActivityTaskCreatedAt = value
	}
	if value, ok := _c.mutation.WorkspaceActivityTaskUpdatedAt(); ok {
		_spec.SetField(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskUpdatedAt, field.TypeTime, value)
		_node.WorkspaceActivityTaskUpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deletedworkspaceactivitytask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(deletedworkspaceactivitytask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedworkspaceactivitytask.TaskTable,
			Columns: []string{deletedworkspaceactivitytask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeletedWorkspaceActivityTask.Create().
//		SetWorkspaceActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeletedWorkspaceActivityTaskUpsert) {
//			SetWorkspaceActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeletedWorkspaceActivityTaskCreate) OnConflict(opts ...sql.ConflictOption) *DeletedWorkspaceActivityTaskUpsertOne {
	_c.conflict = opts
	return &DeletedWorkspaceActivityTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeletedWorkspaceActivityTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeletedWorkspaceActivityTaskCreate) OnConflictColumns(columns ...string) *DeletedWorkspaceActivityTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeletedWorkspaceActivityTaskUpsertOne{
		create: _c,
	}
}

type (
	// DeletedWorkspaceActivityTaskUpsertOne is the builder for "upsert"-ing
	//  one DeletedWorkspaceActivityTask node.
	DeletedWorkspaceActivityTaskUpsertOne struct {
		create *DeletedWorkspaceActivityTaskCreate
	}

	// DeletedWorkspaceActivityTaskUpsert is the "OnConflict" setter.
	DeletedWorkspaceActivityTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetWorkspaceActivityID sets the "workspace_activity_id" field.
func (u *DeletedWorkspaceActivityTaskUpsert) SetWorkspaceActivityID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsert {
	u.Set(deletedworkspaceactivitytask.FieldWorkspaceActivityID, v)
	return u
}

// UpdateWorkspaceActivityID sets the "workspace_activity_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsert) UpdateWorkspaceActivityID() *DeletedWorkspaceActivityTaskUpsert {
	u.SetExcluded(deletedworkspaceactivitytask.FieldWorkspaceActivityID)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *DeletedWorkspaceActivityTaskUpsert) SetTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsert {
	u.Set(deletedworkspaceactivitytask.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsert) UpdateTaskID() *DeletedWorkspaceActivityTaskUpsert {
	u.SetExcluded(deletedworkspaceactivitytask.FieldTaskID)
	return u
}

// SetWorkspaceActivityTaskID sets the "workspace_activity_task_id" field.
func (u *DeletedWorkspaceActivityTaskUpsert) SetWorkspaceActivityTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsert {
	u.Set(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskID, v)
	return u
}

// UpdateWorkspaceActivityTaskID sets the "workspace_activity_task_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsert) UpdateWorkspaceActivityTaskID() *DeletedWorkspaceActivityTaskUpsert {
	u.SetExcluded(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskID)
	return u
}

// SetWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field.
func (u *DeletedWorkspaceActivityTaskUpsert) SetWorkspaceActivityTaskCreatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsert {
	u.Set(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskCreatedAt, v)
	return u
}

// UpdateWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsert) UpdateWorkspaceActivityTaskCreatedAt() *DeletedWorkspaceActivityTaskUpsert {
	u.SetExcluded(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskCreatedAt)
	return u
}

// SetWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field.
func (u *DeletedWorkspaceActivityTaskUpsert) SetWorkspaceActivityTaskUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsert {
	u.Set(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskUpdatedAt, v)
	return u
}

// UpdateWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsert) UpdateWorkspaceActivityTaskUpdatedAt() *DeletedWorkspaceActivityTaskUpsert {
	u.SetExcluded(deletedworkspaceactivitytask.FieldWorkspaceActivityTaskUpdatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeletedWorkspaceActivityTaskUpsert) SetUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsert {
	u.Set(deletedworkspaceactivitytask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsert) UpdateUpdatedAt() *DeletedWorkspaceActivityTaskUpsert {
	u.SetExcluded(deletedworkspaceactivitytask.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DeletedWorkspaceActivityTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deletedworkspaceactivitytask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateNewValues() *DeletedWorkspaceActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(deletedworkspaceactivitytask.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(deletedworkspaceactivitytask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeletedWorkspaceActivityTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeletedWorkspaceActivityTaskUpsertOne) Ignore() *DeletedWorkspaceActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeletedWorkspaceActivityTaskUpsertOne) DoNothing() *DeletedWorkspaceActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeletedWorkspaceActivityTaskCreate.OnConflict
// documentation for more info.
func (u *DeletedWorkspaceActivityTaskUpsertOne) Update(set func(*DeletedWorkspaceActivityTaskUpsert)) *DeletedWorkspaceActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeletedWorkspaceActivityTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceActivityID sets the "workspace_activity_id" field.
func (u *DeletedWorkspaceActivityTaskUpsertOne) SetWorkspaceActivityID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityID(v)
	})
}

// UpdateWorkspaceActivityID sets the "workspace_activity_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateWorkspaceActivityID() *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *DeletedWorkspaceActivityTaskUpsertOne) SetTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateTaskID() *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateTaskID()
	})
}

// SetWorkspaceActivityTaskID sets the "workspace_activity_task_id" field.
func (u *DeletedWorkspaceActivityTaskUpsertOne) SetWorkspaceActivityTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityTaskID(v)
	})
}

// UpdateWorkspaceActivityTaskID sets the "workspace_activity_task_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateWorkspaceActivityTaskID() *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityTaskID()
	})
}

// SetWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field.
func (u *DeletedWorkspaceActivityTaskUpsertOne) SetWorkspaceActivityTaskCreatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityTaskCreatedAt(v)
	})
}

// UpdateWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateWorkspaceActivityTaskCreatedAt() *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityTaskCreatedAt()
	})
}

// SetWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field.
func (u *DeletedWorkspaceActivityTaskUpsertOne) SetWorkspaceActivityTaskUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityTaskUpdatedAt(v)
	})
}

// UpdateWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateWorkspaceActivityTaskUpdatedAt() *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityTaskUpdatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeletedWorkspaceActivityTaskUpsertOne) SetUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertOne) UpdateUpdatedAt() *DeletedWorkspaceActivityTaskUpsertOne {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeletedWorkspaceActivityTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeletedWorkspaceActivityTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeletedWorkspaceActivityTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeletedWorkspaceActivityTaskUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeletedWorkspaceActivityTaskUpsertOne.ID is not supported by MySQL driver. Use DeletedWorkspaceActivityTaskUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeletedWorkspaceActivityTaskUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeletedWorkspaceActivityTaskCreateBulk is the builder for creating many DeletedWorkspaceActivityTask entities in bulk.
type DeletedWorkspaceActivityTaskCreateBulk struct {
	config
	err      error
	builders []*DeletedWorkspaceActivityTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the DeletedWorkspaceActivityTask entities in the database.
func (_c *DeletedWorkspaceActivityTaskCreateBulk) Save(ctx context.Context) ([]*DeletedWorkspaceActivityTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeletedWorkspaceActivityTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeletedWorkspaceActivityTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeletedWorkspaceActivityTaskCreateBulk) SaveX(ctx context.Context) []*DeletedWorkspaceActivityTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeletedWorkspaceActivityTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeletedWorkspaceActivityTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeletedWorkspaceActivityTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeletedWorkspaceActivityTaskUpsert) {
//			SetWorkspaceActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeletedWorkspaceActivityTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeletedWorkspaceActivityTaskUpsertBulk {
	_c.conflict = opts
	return &DeletedWorkspaceActivityTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeletedWorkspaceActivityTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeletedWorkspaceActivityTaskCreateBulk) OnConflictColumns(columns ...string) *DeletedWorkspaceActivityTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeletedWorkspaceActivityTaskUpsertBulk{
		create: _c,
	}
}

// DeletedWorkspaceActivityTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of DeletedWorkspaceActivityTask nodes.
type DeletedWorkspaceActivityTaskUpsertBulk struct {
	create *DeletedWorkspaceActivityTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeletedWorkspaceActivityTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deletedworkspaceactivitytask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateNewValues() *DeletedWorkspaceActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(deletedworkspaceactivitytask.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(deletedworkspaceactivitytask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeletedWorkspaceActivityTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeletedWorkspaceActivityTaskUpsertBulk) Ignore() *DeletedWorkspaceActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) DoNothing() *DeletedWorkspaceActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeletedWorkspaceActivityTaskCreateBulk.OnConflict
// documentation for more info.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) Update(set func(*DeletedWorkspaceActivityTaskUpsert)) *DeletedWorkspaceActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeletedWorkspaceActivityTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceActivityID sets the "workspace_activity_id" field.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) SetWorkspaceActivityID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityID(v)
	})
}

// UpdateWorkspaceActivityID sets the "workspace_activity_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateWorkspaceActivityID() *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) SetTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateTaskID() *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateTaskID()
	})
}

// SetWorkspaceActivityTaskID sets the "workspace_activity_task_id" field.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) SetWorkspaceActivityTaskID(v ulid.ID) *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityTaskID(v)
	})
}

// UpdateWorkspaceActivityTaskID sets the "workspace_activity_task_id" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateWorkspaceActivityTaskID() *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityTaskID()
	})
}

// SetWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) SetWorkspaceActivityTaskCreatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityTaskCreatedAt(v)
	})
}

// UpdateWorkspaceActivityTaskCreatedAt sets the "workspace_activity_task_created_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateWorkspaceActivityTaskCreatedAt() *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityTaskCreatedAt()
	})
}

// SetWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) SetWorkspaceActivityTaskUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetWorkspaceActivityTaskUpdatedAt(v)
	})
}

// UpdateWorkspaceActivityTaskUpdatedAt sets the "workspace_activity_task_updated_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateWorkspaceActivityTaskUpdatedAt() *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateWorkspaceActivityTaskUpdatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) SetUpdatedAt(v time.Time) *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) UpdateUpdatedAt() *DeletedWorkspaceActivityTaskUpsertBulk {
	return u.Update(func(s *DeletedWorkspaceActivityTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeletedWorkspaceActivityTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeletedWorkspaceActivityTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeletedWorkspaceActivityTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
