// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/deletedtask"
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/task"
	"project-management-demo-backend/ent/workspace"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeletedTaskUpdate is the builder for updating DeletedTask entities.
type DeletedTaskUpdate struct {
	config
	hooks    []Hook
	mutation *DeletedTaskMutation
}

// Where appends a list predicates to the DeletedTaskUpdate builder.
func (_u *DeletedTaskUpdate) Where(ps ...predicate.DeletedTask) *DeletedTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *DeletedTaskUpdate) SetTaskID(v ulid.ID) *DeletedTaskUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *DeletedTaskUpdate) SetNillableTaskID(v *ulid.ID) *DeletedTaskUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *DeletedTaskUpdate) SetWorkspaceID(v ulid.ID) *DeletedTaskUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *DeletedTaskUpdate) SetNillableWorkspaceID(v *ulid.ID) *DeletedTaskUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeletedTaskUpdate) SetUpdatedAt(v time.Time) *DeletedTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *DeletedTaskUpdate) SetTask(v *Task) *DeletedTaskUpdate {
	return _u.SetTaskID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *DeletedTaskUpdate) SetWorkspace(v *Workspace) *DeletedTaskUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the DeletedTaskMutation object of the builder.
func (_u *DeletedTaskUpdate) Mutation() *DeletedTaskMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *DeletedTaskUpdate) ClearTask() *DeletedTaskUpdate {
	_u.mutation.ClearTask()
	return _u
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *DeletedTaskUpdate) ClearWorkspace() *DeletedTaskUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeletedTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeletedTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeletedTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeletedTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeletedTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deletedtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeletedTaskUpdate) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeletedTask.task"`)
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeletedTask.workspace"`)
	}
	return nil
}

func (_u *DeletedTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deletedtask.Table, deletedtask.Columns, sqlgraph.NewFieldSpec(deletedtask.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deletedtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.TaskTable,
			Columns: []string{deletedtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.TaskTable,
			Columns: []string{deletedtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.WorkspaceTable,
			Columns: []string{deletedtask.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.WorkspaceTable,
			Columns: []string{deletedtask.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deletedtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeletedTaskUpdateOne is the builder for updating a single DeletedTask entity.
type DeletedTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeletedTaskMutation
}

// SetTaskID sets the "task_id" field.
func (_u *DeletedTaskUpdateOne) SetTaskID(v ulid.ID) *DeletedTaskUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *DeletedTaskUpdateOne) SetNillableTaskID(v *ulid.ID) *DeletedTaskUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *DeletedTaskUpdateOne) SetWorkspaceID(v ulid.ID) *DeletedTaskUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *DeletedTaskUpdateOne) SetNillableWorkspaceID(v *ulid.ID) *DeletedTaskUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeletedTaskUpdateOne) SetUpdatedAt(v time.Time) *DeletedTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *DeletedTaskUpdateOne) SetTask(v *Task) *DeletedTaskUpdateOne {
	return _u.SetTaskID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *DeletedTaskUpdateOne) SetWorkspace(v *Workspace) *DeletedTaskUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the DeletedTaskMutation object of the builder.
func (_u *DeletedTaskUpdateOne) Mutation() *DeletedTaskMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *DeletedTaskUpdateOne) ClearTask() *DeletedTaskUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *DeletedTaskUpdateOne) ClearWorkspace() *DeletedTaskUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// Where appends a list predicates to the DeletedTaskUpdate builder.
func (_u *DeletedTaskUpdateOne) Where(ps ...predicate.DeletedTask) *DeletedTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeletedTaskUpdateOne) Select(field string, fields ...string) *DeletedTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeletedTask entity.
func (_u *DeletedTaskUpdateOne) Save(ctx context.Context) (*DeletedTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeletedTaskUpdateOne) SaveX(ctx context.Context) *DeletedTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeletedTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeletedTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeletedTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deletedtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeletedTaskUpdateOne) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeletedTask.task"`)
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeletedTask.workspace"`)
	}
	return nil
}

func (_u *DeletedTaskUpdateOne) sqlSave(ctx context.Context) (_node *DeletedTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deletedtask.Table, deletedtask.Columns, sqlgraph.NewFieldSpec(deletedtask.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeletedTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deletedtask.FieldID)
		for _, f := range fields {
			if !deletedtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deletedtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deletedtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.TaskTable,
			Columns: []string{deletedtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.TaskTable,
			Columns: []string{deletedtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.WorkspaceTable,
			Columns: []string{deletedtask.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deletedtask.WorkspaceTable,
			Columns: []string{deletedtask.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeletedTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deletedtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
