// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/project"
	"project-management-demo-backend/ent/projecttaskliststatus"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/tasklistcompletedstatus"
	"project-management-demo-backend/ent/tasklistsortstatus"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectTaskListStatusCreate is the builder for creating a ProjectTaskListStatus entity.
type ProjectTaskListStatusCreate struct {
	config
	mutation *ProjectTaskListStatusMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProjectID sets the "project_id" field.
func (_c *ProjectTaskListStatusCreate) SetProjectID(v ulid.ID) *ProjectTaskListStatusCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetTaskListCompletedStatusID sets the "task_list_completed_status_id" field.
func (_c *ProjectTaskListStatusCreate) SetTaskListCompletedStatusID(v ulid.ID) *ProjectTaskListStatusCreate {
	_c.mutation.SetTaskListCompletedStatusID(v)
	return _c
}

// SetTaskListSortStatusID sets the "task_list_sort_status_id" field.
func (_c *ProjectTaskListStatusCreate) SetTaskListSortStatusID(v ulid.ID) *ProjectTaskListStatusCreate {
	_c.mutation.SetTaskListSortStatusID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectTaskListStatusCreate) SetCreatedAt(v time.Time) *ProjectTaskListStatusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectTaskListStatusCreate) SetNillableCreatedAt(v *time.Time) *ProjectTaskListStatusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectTaskListStatusCreate) SetUpdatedAt(v time.Time) *ProjectTaskListStatusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectTaskListStatusCreate) SetNillableUpdatedAt(v *time.Time) *ProjectTaskListStatusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectTaskListStatusCreate) SetID(v ulid.ID) *ProjectTaskListStatusCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectTaskListStatusCreate) SetNillableID(v *ulid.ID) *ProjectTaskListStatusCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectTaskListStatusCreate) SetProject(v *Project) *ProjectTaskListStatusCreate {
	return _c.SetProjectID(v.ID)
}

// SetTaskListCompletedStatus sets the "taskListCompletedStatus" edge to the TaskListCompletedStatus entity.
func (_c *ProjectTaskListStatusCreate) SetTaskListCompletedStatus(v *TaskListCompletedStatus) *ProjectTaskListStatusCreate {
	return _c.SetTaskListCompletedStatusID(v.ID)
}

// SetTaskListSortStatus sets the "taskListSortStatus" edge to the TaskListSortStatus entity.
func (_c *ProjectTaskListStatusCreate) SetTaskListSortStatus(v *TaskListSortStatus) *ProjectTaskListStatusCreate {
	return _c.SetTaskListSortStatusID(v.ID)
}

// Mutation returns the ProjectTaskListStatusMutation object of the builder.
func (_c *ProjectTaskListStatusCreate) Mutation() *ProjectTaskListStatusMutation {
	return _c.mutation
}

// Save creates the ProjectTaskListStatus in the database.
func (_c *ProjectTaskListStatusCreate) Save(ctx context.Context) (*ProjectTaskListStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectTaskListStatusCreate) SaveX(ctx context.Context) *ProjectTaskListStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectTaskListStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectTaskListStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectTaskListStatusCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projecttaskliststatus.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := projecttaskliststatus.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := projecttaskliststatus.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectTaskListStatusCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ProjectTaskListStatus.project_id"`)}
	}
	if _, ok := _c.mutation.TaskListCompletedStatusID(); !ok {
		return &ValidationError{Name: "task_list_completed_status_id", err: errors.New(`ent: missing required field "ProjectTaskListStatus.task_list_completed_status_id"`)}
	}
	if _, ok := _c.mutation.TaskListSortStatusID(); !ok {
		return &ValidationError{Name: "task_list_sort_status_id", err: errors.New(`ent: missing required field "ProjectTaskListStatus.task_list_sort_status_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectTaskListStatus.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProjectTaskListStatus.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectTaskListStatus.project"`)}
	}
	if len(_c.mutation.TaskListCompletedStatusIDs()) == 0 {
		return &ValidationError{Name: "taskListCompletedStatus", err: errors.New(`ent: missing required edge "ProjectTaskListStatus.taskListCompletedStatus"`)}
	}
	if len(_c.mutation.TaskListSortStatusIDs()) == 0 {
		return &ValidationError{Name: "taskListSortStatus", err: errors.New(`ent: missing required edge "ProjectTaskListStatus.taskListSortStatus"`)}
	}
	return nil
}

func (_c *ProjectTaskListStatusCreate) sqlSave(ctx context.Context) (*ProjectTaskListStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectTaskListStatusCreate) createSpec() (*ProjectTaskListStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectTaskListStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projecttaskliststatus.Table, sqlgraph.NewFieldSpec(projecttaskliststatus.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projecttaskliststatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttaskliststatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskliststatus.ProjectTable,
			Columns: []string{projecttaskliststatus.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskListCompletedStatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskliststatus.TaskListCompletedStatusTable,
			Columns: []string{projecttaskliststatus.TaskListCompletedStatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasklistcompletedstatus.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskListCompletedStatusID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskListSortStatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskliststatus.TaskListSortStatusTable,
			Columns: []string{projecttaskliststatus.TaskListSortStatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasklistsortstatus.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskListSortStatusID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProjectTaskListStatus.Create().
//		SetProjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectTaskListStatusUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectTaskListStatusCreate) OnConflict(opts ...sql.ConflictOption) *ProjectTaskListStatusUpsertOne {
	_c.conflict = opts
	return &ProjectTaskListStatusUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProjectTaskListStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectTaskListStatusCreate) OnConflictColumns(columns ...string) *ProjectTaskListStatusUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectTaskListStatusUpsertOne{
		create: _c,
	}
}

type (
	// ProjectTaskListStatusUpsertOne is the builder for "upsert"-ing
	//  one ProjectTaskListStatus node.
	ProjectTaskListStatusUpsertOne struct {
		create *ProjectTaskListStatusCreate
	}

	// ProjectTaskListStatusUpsert is the "OnConflict" setter.
	ProjectTaskListStatusUpsert struct {
		*sql.UpdateSet
	}
)

// SetProjectID sets the "project_id" field.
func (u *ProjectTaskListStatusUpsert) SetProjectID(v ulid.ID) *ProjectTaskListStatusUpsert {
	u.Set(projecttaskliststatus.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsert) UpdateProjectID() *ProjectTaskListStatusUpsert {
	u.SetExcluded(projecttaskliststatus.FieldProjectID)
	return u
}

// SetTaskListCompletedStatusID sets the "task_list_completed_status_id" field.
func (u *ProjectTaskListStatusUpsert) SetTaskListCompletedStatusID(v ulid.ID) *ProjectTaskListStatusUpsert {
	u.Set(projecttaskliststatus.FieldTaskListCompletedStatusID, v)
	return u
}

// UpdateTaskListCompletedStatusID sets the "task_list_completed_status_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsert) UpdateTaskListCompletedStatusID() *ProjectTaskListStatusUpsert {
	u.SetExcluded(projecttaskliststatus.FieldTaskListCompletedStatusID)
	return u
}

// SetTaskListSortStatusID sets the "task_list_sort_status_id" field.
func (u *ProjectTaskListStatusUpsert) SetTaskListSortStatusID(v ulid.ID) *ProjectTaskListStatusUpsert {
	u.Set(projecttaskliststatus.FieldTaskListSortStatusID, v)
	return u
}

// UpdateTaskListSortStatusID sets the "task_list_sort_status_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsert) UpdateTaskListSortStatusID() *ProjectTaskListStatusUpsert {
	u.SetExcluded(projecttaskliststatus.FieldTaskListSortStatusID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProjectTaskListStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(projecttaskliststatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProjectTaskListStatusUpsertOne) UpdateNewValues() *ProjectTaskListStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(projecttaskliststatus.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(projecttaskliststatus.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UpdatedAt(); exists {
			s.SetIgnore(projecttaskliststatus.FieldUpdatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProjectTaskListStatus.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProjectTaskListStatusUpsertOne) Ignore() *ProjectTaskListStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectTaskListStatusUpsertOne) DoNothing() *ProjectTaskListStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectTaskListStatusCreate.OnConflict
// documentation for more info.
func (u *ProjectTaskListStatusUpsertOne) Update(set func(*ProjectTaskListStatusUpsert)) *ProjectTaskListStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectTaskListStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ProjectTaskListStatusUpsertOne) SetProjectID(v ulid.ID) *ProjectTaskListStatusUpsertOne {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsertOne) UpdateProjectID() *ProjectTaskListStatusUpsertOne {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.UpdateProjectID()
	})
}

// SetTaskListCompletedStatusID sets the "task_list_completed_status_id" field.
func (u *ProjectTaskListStatusUpsertOne) SetTaskListCompletedStatusID(v ulid.ID) *ProjectTaskListStatusUpsertOne {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.SetTaskListCompletedStatusID(v)
	})
}

// UpdateTaskListCompletedStatusID sets the "task_list_completed_status_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsertOne) UpdateTaskListCompletedStatusID() *ProjectTaskListStatusUpsertOne {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.UpdateTaskListCompletedStatusID()
	})
}

// SetTaskListSortStatusID sets the "task_list_sort_status_id" field.
func (u *ProjectTaskListStatusUpsertOne) SetTaskListSortStatusID(v ulid.ID) *ProjectTaskListStatusUpsertOne {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.SetTaskListSortStatusID(v)
	})
}

// UpdateTaskListSortStatusID sets the "task_list_sort_status_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsertOne) UpdateTaskListSortStatusID() *ProjectTaskListStatusUpsertOne {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.UpdateTaskListSortStatusID()
	})
}

// Exec executes the query.
func (u *ProjectTaskListStatusUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectTaskListStatusCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectTaskListStatusUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProjectTaskListStatusUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProjectTaskListStatusUpsertOne.ID is not supported by MySQL driver. Use ProjectTaskListStatusUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProjectTaskListStatusUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProjectTaskListStatusCreateBulk is the builder for creating many ProjectTaskListStatus entities in bulk.
type ProjectTaskListStatusCreateBulk struct {
	config
	err      error
	builders []*ProjectTaskListStatusCreate
	conflict []sql.ConflictOption
}

// Save creates the ProjectTaskListStatus entities in the database.
func (_c *ProjectTaskListStatusCreateBulk) Save(ctx context.Context) ([]*ProjectTaskListStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectTaskListStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectTaskListStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectTaskListStatusCreateBulk) SaveX(ctx context.Context) []*ProjectTaskListStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectTaskListStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectTaskListStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProjectTaskListStatus.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectTaskListStatusUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectTaskListStatusCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProjectTaskListStatusUpsertBulk {
	_c.conflict = opts
	return &ProjectTaskListStatusUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProjectTaskListStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectTaskListStatusCreateBulk) OnConflictColumns(columns ...string) *ProjectTaskListStatusUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectTaskListStatusUpsertBulk{
		create: _c,
	}
}

// ProjectTaskListStatusUpsertBulk is the builder for "upsert"-ing
// a bulk of ProjectTaskListStatus nodes.
type ProjectTaskListStatusUpsertBulk struct {
	create *ProjectTaskListStatusCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProjectTaskListStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(projecttaskliststatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProjectTaskListStatusUpsertBulk) UpdateNewValues() *ProjectTaskListStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(projecttaskliststatus.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(projecttaskliststatus.FieldCreatedAt)
			}
			if _, exists := b.mutation.UpdatedAt(); exists {
				s.SetIgnore(projecttaskliststatus.FieldUpdatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProjectTaskListStatus.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProjectTaskListStatusUpsertBulk) Ignore() *ProjectTaskListStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectTaskListStatusUpsertBulk) DoNothing() *ProjectTaskListStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectTaskListStatusCreateBulk.OnConflict
// documentation for more info.
func (u *ProjectTaskListStatusUpsertBulk) Update(set func(*ProjectTaskListStatusUpsert)) *ProjectTaskListStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectTaskListStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ProjectTaskListStatusUpsertBulk) SetProjectID(v ulid.ID) *ProjectTaskListStatusUpsertBulk {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsertBulk) UpdateProjectID() *ProjectTaskListStatusUpsertBulk {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.UpdateProjectID()
	})
}

// SetTaskListCompletedStatusID sets the "task_list_completed_status_id" field.
func (u *ProjectTaskListStatusUpsertBulk) SetTaskListCompletedStatusID(v ulid.ID) *ProjectTaskListStatusUpsertBulk {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.SetTaskListCompletedStatusID(v)
	})
}

// UpdateTaskListCompletedStatusID sets the "task_list_completed_status_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsertBulk) UpdateTaskListCompletedStatusID() *ProjectTaskListStatusUpsertBulk {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.UpdateTaskListCompletedStatusID()
	})
}

// SetTaskListSortStatusID sets the "task_list_sort_status_id" field.
func (u *ProjectTaskListStatusUpsertBulk) SetTaskListSortStatusID(v ulid.ID) *ProjectTaskListStatusUpsertBulk {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.SetTaskListSortStatusID(v)
	})
}

// UpdateTaskListSortStatusID sets the "task_list_sort_status_id" field to the value that was provided on create.
func (u *ProjectTaskListStatusUpsertBulk) UpdateTaskListSortStatusID() *ProjectTaskListStatusUpsertBulk {
	return u.Update(func(s *ProjectTaskListStatusUpsert) {
		s.UpdateTaskListSortStatusID()
	})
}

// Exec executes the query.
func (u *ProjectTaskListStatusUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProjectTaskListStatusCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectTaskListStatusCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectTaskListStatusUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
