// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/project"
	"project-management-demo-backend/ent/projecttaskcolumn"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/taskcolumn"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectTaskColumnUpdate is the builder for updating ProjectTaskColumn entities.
type ProjectTaskColumnUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectTaskColumnMutation
}

// Where appends a list predicates to the ProjectTaskColumnUpdate builder.
func (_u *ProjectTaskColumnUpdate) Where(ps ...predicate.ProjectTaskColumn) *ProjectTaskColumnUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectTaskColumnUpdate) SetProjectID(v ulid.ID) *ProjectTaskColumnUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdate) SetNillableProjectID(v *ulid.ID) *ProjectTaskColumnUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTaskColumnID sets the "task_column_id" field.
func (_u *ProjectTaskColumnUpdate) SetTaskColumnID(v ulid.ID) *ProjectTaskColumnUpdate {
	_u.mutation.SetTaskColumnID(v)
	return _u
}

// SetNillableTaskColumnID sets the "task_column_id" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdate) SetNillableTaskColumnID(v *ulid.ID) *ProjectTaskColumnUpdate {
	if v != nil {
		_u.SetTaskColumnID(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ProjectTaskColumnUpdate) SetWidth(v string) *ProjectTaskColumnUpdate {
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdate) SetNillableWidth(v *string) *ProjectTaskColumnUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *ProjectTaskColumnUpdate) SetDisabled(v bool) *ProjectTaskColumnUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdate) SetNillableDisabled(v *bool) *ProjectTaskColumnUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetCustomizable sets the "customizable" field.
func (_u *ProjectTaskColumnUpdate) SetCustomizable(v bool) *ProjectTaskColumnUpdate {
	_u.mutation.SetCustomizable(v)
	return _u
}

// SetNillableCustomizable sets the "customizable" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdate) SetNillableCustomizable(v *bool) *ProjectTaskColumnUpdate {
	if v != nil {
		_u.SetCustomizable(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *ProjectTaskColumnUpdate) SetOrder(v int) *ProjectTaskColumnUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdate) SetNillableOrder(v *int) *ProjectTaskColumnUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *ProjectTaskColumnUpdate) AddOrder(v int) *ProjectTaskColumnUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectTaskColumnUpdate) SetUpdatedAt(v time.Time) *ProjectTaskColumnUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectTaskColumnUpdate) SetProject(v *Project) *ProjectTaskColumnUpdate {
	return _u.SetProjectID(v.ID)
}

// SetTaskColumn sets the "taskColumn" edge to the TaskColumn entity.
func (_u *ProjectTaskColumnUpdate) SetTaskColumn(v *TaskColumn) *ProjectTaskColumnUpdate {
	return _u.SetTaskColumnID(v.ID)
}

// Mutation returns the ProjectTaskColumnMutation object of the builder.
func (_u *ProjectTaskColumnUpdate) Mutation() *ProjectTaskColumnMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectTaskColumnUpdate) ClearProject() *ProjectTaskColumnUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearTaskColumn clears the "taskColumn" edge to the TaskColumn entity.
func (_u *ProjectTaskColumnUpdate) ClearTaskColumn() *ProjectTaskColumnUpdate {
	_u.mutation.ClearTaskColumn()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectTaskColumnUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTaskColumnUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectTaskColumnUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTaskColumnUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectTaskColumnUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := projecttaskcolumn.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTaskColumnUpdate) check() error {
	if v, ok := _u.mutation.Width(); ok {
		if err := projecttaskcolumn.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskColumn.width": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTaskColumn.project"`)
	}
	if _u.mutation.TaskColumnCleared() && len(_u.mutation.TaskColumnIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTaskColumn.taskColumn"`)
	}
	return nil
}

func (_u *ProjectTaskColumnUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttaskcolumn.Table, projecttaskcolumn.Columns, sqlgraph.NewFieldSpec(projecttaskcolumn.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(projecttaskcolumn.FieldWidth, field.TypeString, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(projecttaskcolumn.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Customizable(); ok {
		_spec.SetField(projecttaskcolumn.FieldCustomizable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(projecttaskcolumn.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(projecttaskcolumn.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttaskcolumn.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.ProjectTable,
			Columns: []string{projecttaskcolumn.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.ProjectTable,
			Columns: []string{projecttaskcolumn.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskColumnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.TaskColumnTable,
			Columns: []string{projecttaskcolumn.TaskColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcolumn.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskColumnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.TaskColumnTable,
			Columns: []string{projecttaskcolumn.TaskColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcolumn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttaskcolumn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectTaskColumnUpdateOne is the builder for updating a single ProjectTaskColumn entity.
type ProjectTaskColumnUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectTaskColumnMutation
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectTaskColumnUpdateOne) SetProjectID(v ulid.ID) *ProjectTaskColumnUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdateOne) SetNillableProjectID(v *ulid.ID) *ProjectTaskColumnUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTaskColumnID sets the "task_column_id" field.
func (_u *ProjectTaskColumnUpdateOne) SetTaskColumnID(v ulid.ID) *ProjectTaskColumnUpdateOne {
	_u.mutation.SetTaskColumnID(v)
	return _u
}

// SetNillableTaskColumnID sets the "task_column_id" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdateOne) SetNillableTaskColumnID(v *ulid.ID) *ProjectTaskColumnUpdateOne {
	if v != nil {
		_u.SetTaskColumnID(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ProjectTaskColumnUpdateOne) SetWidth(v string) *ProjectTaskColumnUpdateOne {
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdateOne) SetNillableWidth(v *string) *ProjectTaskColumnUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *ProjectTaskColumnUpdateOne) SetDisabled(v bool) *ProjectTaskColumnUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdateOne) SetNillableDisabled(v *bool) *ProjectTaskColumnUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetCustomizable sets the "customizable" field.
func (_u *ProjectTaskColumnUpdateOne) SetCustomizable(v bool) *ProjectTaskColumnUpdateOne {
	_u.mutation.SetCustomizable(v)
	return _u
}

// SetNillableCustomizable sets the "customizable" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdateOne) SetNillableCustomizable(v *bool) *ProjectTaskColumnUpdateOne {
	if v != nil {
		_u.SetCustomizable(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *ProjectTaskColumnUpdateOne) SetOrder(v int) *ProjectTaskColumnUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *ProjectTaskColumnUpdateOne) SetNillableOrder(v *int) *ProjectTaskColumnUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *ProjectTaskColumnUpdateOne) AddOrder(v int) *ProjectTaskColumnUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectTaskColumnUpdateOne) SetUpdatedAt(v time.Time) *ProjectTaskColumnUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectTaskColumnUpdateOne) SetProject(v *Project) *ProjectTaskColumnUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetTaskColumn sets the "taskColumn" edge to the TaskColumn entity.
func (_u *ProjectTaskColumnUpdateOne) SetTaskColumn(v *TaskColumn) *ProjectTaskColumnUpdateOne {
	return _u.SetTaskColumnID(v.ID)
}

// Mutation returns the ProjectTaskColumnMutation object of the builder.
func (_u *ProjectTaskColumnUpdateOne) Mutation() *ProjectTaskColumnMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectTaskColumnUpdateOne) ClearProject() *ProjectTaskColumnUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearTaskColumn clears the "taskColumn" edge to the TaskColumn entity.
func (_u *ProjectTaskColumnUpdateOne) ClearTaskColumn() *ProjectTaskColumnUpdateOne {
	_u.mutation.ClearTaskColumn()
	return _u
}

// Where appends a list predicates to the ProjectTaskColumnUpdate builder.
func (_u *ProjectTaskColumnUpdateOne) Where(ps ...predicate.ProjectTaskColumn) *ProjectTaskColumnUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectTaskColumnUpdateOne) Select(field string, fields ...string) *ProjectTaskColumnUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectTaskColumn entity.
func (_u *ProjectTaskColumnUpdateOne) Save(ctx context.Context) (*ProjectTaskColumn, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTaskColumnUpdateOne) SaveX(ctx context.Context) *ProjectTaskColumn {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectTaskColumnUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTaskColumnUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectTaskColumnUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := projecttaskcolumn.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTaskColumnUpdateOne) check() error {
	if v, ok := _u.mutation.Width(); ok {
		if err := projecttaskcolumn.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskColumn.width": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTaskColumn.project"`)
	}
	if _u.mutation.TaskColumnCleared() && len(_u.mutation.TaskColumnIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTaskColumn.taskColumn"`)
	}
	return nil
}

func (_u *ProjectTaskColumnUpdateOne) sqlSave(ctx context.Context) (_node *ProjectTaskColumn, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttaskcolumn.Table, projecttaskcolumn.Columns, sqlgraph.NewFieldSpec(projecttaskcolumn.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectTaskColumn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projecttaskcolumn.FieldID)
		for _, f := range fields {
			if !projecttaskcolumn.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projecttaskcolumn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(projecttaskcolumn.FieldWidth, field.TypeString, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(projecttaskcolumn.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Customizable(); ok {
		_spec.SetField(projecttaskcolumn.FieldCustomizable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(projecttaskcolumn.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(projecttaskcolumn.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttaskcolumn.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.ProjectTable,
			Columns: []string{projecttaskcolumn.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.ProjectTable,
			Columns: []string{projecttaskcolumn.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskColumnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.TaskColumnTable,
			Columns: []string{projecttaskcolumn.TaskColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcolumn.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskColumnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttaskcolumn.TaskColumnTable,
			Columns: []string{projecttaskcolumn.TaskColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcolumn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectTaskColumn{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttaskcolumn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
