// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/taskcollaborator"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCollaboratorDelete is the builder for deleting a TaskCollaborator entity.
type TaskCollaboratorDelete struct {
	config
	hooks    []Hook
	mutation *TaskCollaboratorMutation
}

// Where appends a list predicates to the TaskCollaboratorDelete builder.
func (_d *TaskCollaboratorDelete) Where(ps ...predicate.TaskCollaborator) *TaskCollaboratorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TaskCollaboratorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskCollaboratorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TaskCollaboratorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskcollaborator.Table, sqlgraph.NewFieldSpec(taskcollaborator.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TaskCollaboratorDeleteOne is the builder for deleting a single TaskCollaborator entity.
type TaskCollaboratorDeleteOne struct {
	_d *TaskCollaboratorDelete
}

// Where appends a list predicates to the TaskCollaboratorDelete builder.
func (_d *TaskCollaboratorDeleteOne) Where(ps ...predicate.TaskCollaborator) *TaskCollaboratorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TaskCollaboratorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskcollaborator.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskCollaboratorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
