// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/activitytype"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/taskactivity"
	"project-management-demo-backend/ent/taskactivitytask"
	"project-management-demo-backend/ent/teammate"
	"project-management-demo-backend/ent/workspace"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskActivityCreate is the builder for creating a TaskActivity entity.
type TaskActivityCreate struct {
	config
	mutation *TaskActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityTypeID sets the "activity_type_id" field.
func (_c *TaskActivityCreate) SetActivityTypeID(v ulid.ID) *TaskActivityCreate {
	_c.mutation.SetActivityTypeID(v)
	return _c
}

// SetTeammateID sets the "teammate_id" field.
func (_c *TaskActivityCreate) SetTeammateID(v ulid.ID) *TaskActivityCreate {
	_c.mutation.SetTeammateID(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *TaskActivityCreate) SetWorkspaceID(v ulid.ID) *TaskActivityCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskActivityCreate) SetCreatedAt(v time.Time) *TaskActivityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskActivityCreate) SetNillableCreatedAt(v *time.Time) *TaskActivityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskActivityCreate) SetUpdatedAt(v time.Time) *TaskActivityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskActivityCreate) SetNillableUpdatedAt(v *time.Time) *TaskActivityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskActivityCreate) SetID(v ulid.ID) *TaskActivityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TaskActivityCreate) SetNillableID(v *ulid.ID) *TaskActivityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTeammate sets the "teammate" edge to the Teammate entity.
func (_c *TaskActivityCreate) SetTeammate(v *Teammate) *TaskActivityCreate {
	return _c.SetTeammateID(v.ID)
}

// SetActivityType sets the "activityType" edge to the ActivityType entity.
func (_c *TaskActivityCreate) SetActivityType(v *ActivityType) *TaskActivityCreate {
	return _c.SetActivityTypeID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *TaskActivityCreate) SetWorkspace(v *Workspace) *TaskActivityCreate {
	return _c.SetWorkspaceID(v.ID)
}

// AddTaskActivityTaskIDs adds the "taskActivityTasks" edge to the TaskActivityTask entity by IDs.
func (_c *TaskActivityCreate) AddTaskActivityTaskIDs(ids ...ulid.ID) *TaskActivityCreate {
	_c.mutation.AddTaskActivityTaskIDs(ids...)
	return _c
}

// AddTaskActivityTasks adds the "taskActivityTasks" edges to the TaskActivityTask entity.
func (_c *TaskActivityCreate) AddTaskActivityTasks(v ...*TaskActivityTask) *TaskActivityCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskActivityTaskIDs(ids...)
}

// Mutation returns the TaskActivityMutation object of the builder.
func (_c *TaskActivityCreate) Mutation() *TaskActivityMutation {
	return _c.mutation
}

// Save creates the TaskActivity in the database.
func (_c *TaskActivityCreate) Save(ctx context.Context) (*TaskActivity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskActivityCreate) SaveX(ctx context.Context) *TaskActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskActivityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := taskactivity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := taskactivity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := taskactivity.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskActivityCreate) check() error {
	if _, ok := _c.mutation.ActivityTypeID(); !ok {
		return &ValidationError{Name: "activity_type_id", err: errors.New(`ent: missing required field "TaskActivity.activity_type_id"`)}
	}
	if _, ok := _c.mutation.TeammateID(); !ok {
		return &ValidationError{Name: "teammate_id", err: errors.New(`ent: missing required field "TaskActivity.teammate_id"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "TaskActivity.workspace_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskActivity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TaskActivity.updated_at"`)}
	}
	if len(_c.mutation.TeammateIDs()) == 0 {
		return &ValidationError{Name: "teammate", err: errors.New(`ent: missing required edge "TaskActivity.teammate"`)}
	}
	if len(_c.mutation.ActivityTypeIDs()) == 0 {
		return &ValidationError{Name: "activityType", err: errors.New(`ent: missing required edge "TaskActivity.activityType"`)}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "TaskActivity.workspace"`)}
	}
	return nil
}

func (_c *TaskActivityCreate) sqlSave(ctx context.Context) (*TaskActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskActivityCreate) createSpec() (*TaskActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskactivity.Table, sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(taskactivity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(taskactivity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TeammateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskactivity.TeammateTable,
			Columns: []string{taskactivity.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeammateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ActivityTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskactivity.ActivityTypeTable,
			Columns: []string{taskactivity.ActivityTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitytype.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskactivity.WorkspaceTable,
			Columns: []string{taskactivity.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskActivityTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskactivity.TaskActivityTasksTable,
			Columns: []string{taskactivity.TaskActivityTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivitytask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskActivity.Create().
//		SetActivityTypeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskActivityUpsert) {
//			SetActivityTypeID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskActivityCreate) OnConflict(opts ...sql.ConflictOption) *TaskActivityUpsertOne {
	_c.conflict = opts
	return &TaskActivityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskActivityCreate) OnConflictColumns(columns ...string) *TaskActivityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskActivityUpsertOne{
		create: _c,
	}
}

type (
	// TaskActivityUpsertOne is the builder for "upsert"-ing
	//  one TaskActivity node.
	TaskActivityUpsertOne struct {
		create *TaskActivityCreate
	}

	// TaskActivityUpsert is the "OnConflict" setter.
	TaskActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityTypeID sets the "activity_type_id" field.
func (u *TaskActivityUpsert) SetActivityTypeID(v ulid.ID) *TaskActivityUpsert {
	u.Set(taskactivity.FieldActivityTypeID, v)
	return u
}

// UpdateActivityTypeID sets the "activity_type_id" field to the value that was provided on create.
func (u *TaskActivityUpsert) UpdateActivityTypeID() *TaskActivityUpsert {
	u.SetExcluded(taskactivity.FieldActivityTypeID)
	return u
}

// SetTeammateID sets the "teammate_id" field.
func (u *TaskActivityUpsert) SetTeammateID(v ulid.ID) *TaskActivityUpsert {
	u.Set(taskactivity.FieldTeammateID, v)
	return u
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *TaskActivityUpsert) UpdateTeammateID() *TaskActivityUpsert {
	u.SetExcluded(taskactivity.FieldTeammateID)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *TaskActivityUpsert) SetWorkspaceID(v ulid.ID) *TaskActivityUpsert {
	u.Set(taskactivity.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *TaskActivityUpsert) UpdateWorkspaceID() *TaskActivityUpsert {
	u.SetExcluded(taskactivity.FieldWorkspaceID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskActivityUpsert) SetUpdatedAt(v time.Time) *TaskActivityUpsert {
	u.Set(taskactivity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskActivityUpsert) UpdateUpdatedAt() *TaskActivityUpsert {
	u.SetExcluded(taskactivity.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskactivity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskActivityUpsertOne) UpdateNewValues() *TaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskactivity.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(taskactivity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskActivity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskActivityUpsertOne) Ignore() *TaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskActivityUpsertOne) DoNothing() *TaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskActivityCreate.OnConflict
// documentation for more info.
func (u *TaskActivityUpsertOne) Update(set func(*TaskActivityUpsert)) *TaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityTypeID sets the "activity_type_id" field.
func (u *TaskActivityUpsertOne) SetActivityTypeID(v ulid.ID) *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetActivityTypeID(v)
	})
}

// UpdateActivityTypeID sets the "activity_type_id" field to the value that was provided on create.
func (u *TaskActivityUpsertOne) UpdateActivityTypeID() *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateActivityTypeID()
	})
}

// SetTeammateID sets the "teammate_id" field.
func (u *TaskActivityUpsertOne) SetTeammateID(v ulid.ID) *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetTeammateID(v)
	})
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *TaskActivityUpsertOne) UpdateTeammateID() *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateTeammateID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *TaskActivityUpsertOne) SetWorkspaceID(v ulid.ID) *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *TaskActivityUpsertOne) UpdateWorkspaceID() *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskActivityUpsertOne) SetUpdatedAt(v time.Time) *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskActivityUpsertOne) UpdateUpdatedAt() *TaskActivityUpsertOne {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TaskActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskActivityUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TaskActivityUpsertOne.ID is not supported by MySQL driver. Use TaskActivityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskActivityUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskActivityCreateBulk is the builder for creating many TaskActivity entities in bulk.
type TaskActivityCreateBulk struct {
	config
	err      error
	builders []*TaskActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskActivity entities in the database.
func (_c *TaskActivityCreateBulk) Save(ctx context.Context) ([]*TaskActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskActivityCreateBulk) SaveX(ctx context.Context) []*TaskActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskActivity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskActivityUpsert) {
//			SetActivityTypeID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskActivityUpsertBulk {
	_c.conflict = opts
	return &TaskActivityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskActivityCreateBulk) OnConflictColumns(columns ...string) *TaskActivityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskActivityUpsertBulk{
		create: _c,
	}
}

// TaskActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskActivity nodes.
type TaskActivityUpsertBulk struct {
	create *TaskActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskactivity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskActivityUpsertBulk) UpdateNewValues() *TaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskactivity.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(taskactivity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskActivity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskActivityUpsertBulk) Ignore() *TaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskActivityUpsertBulk) DoNothing() *TaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskActivityCreateBulk.OnConflict
// documentation for more info.
func (u *TaskActivityUpsertBulk) Update(set func(*TaskActivityUpsert)) *TaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityTypeID sets the "activity_type_id" field.
func (u *TaskActivityUpsertBulk) SetActivityTypeID(v ulid.ID) *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetActivityTypeID(v)
	})
}

// UpdateActivityTypeID sets the "activity_type_id" field to the value that was provided on create.
func (u *TaskActivityUpsertBulk) UpdateActivityTypeID() *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateActivityTypeID()
	})
}

// SetTeammateID sets the "teammate_id" field.
func (u *TaskActivityUpsertBulk) SetTeammateID(v ulid.ID) *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetTeammateID(v)
	})
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *TaskActivityUpsertBulk) UpdateTeammateID() *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateTeammateID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *TaskActivityUpsertBulk) SetWorkspaceID(v ulid.ID) *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *TaskActivityUpsertBulk) UpdateWorkspaceID() *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskActivityUpsertBulk) SetUpdatedAt(v time.Time) *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskActivityUpsertBulk) UpdateUpdatedAt() *TaskActivityUpsertBulk {
	return u.Update(func(s *TaskActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TaskActivityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
