// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/predicate"
	"asana-clone-app/ent/taskpriority"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskPriorityDelete is the builder for deleting a TaskPriority entity.
type TaskPriorityDelete struct {
	config
	hooks    []Hook
	mutation *TaskPriorityMutation
}

// Where appends a list predicates to the TaskPriorityDelete builder.
func (_d *TaskPriorityDelete) Where(ps ...predicate.TaskPriority) *TaskPriorityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TaskPriorityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskPriorityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TaskPriorityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskpriority.Table, sqlgraph.NewFieldSpec(taskpriority.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TaskPriorityDeleteOne is the builder for deleting a single TaskPriority entity.
type TaskPriorityDeleteOne struct {
	_d *TaskPriorityDelete
}

// Where appends a list predicates to the TaskPriorityDelete builder.
func (_d *TaskPriorityDeleteOne) Where(ps ...predicate.TaskPriority) *TaskPriorityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TaskPriorityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskpriority.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskPriorityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
