// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/predicate"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/ent/task"
	"asana-clone-app/ent/taskfeed"
	"asana-clone-app/ent/taskfeedlike"
	"asana-clone-app/ent/taskfile"
	"asana-clone-app/ent/teammate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskFeedUpdate is the builder for updating TaskFeed entities.
type TaskFeedUpdate struct {
	config
	hooks    []Hook
	mutation *TaskFeedMutation
}

// Where appends a list predicates to the TaskFeedUpdate builder.
func (_u *TaskFeedUpdate) Where(ps ...predicate.TaskFeed) *TaskFeedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TaskFeedUpdate) SetTaskID(v ulid.ID) *TaskFeedUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskFeedUpdate) SetNillableTaskID(v *ulid.ID) *TaskFeedUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetTeammateID sets the "teammate_id" field.
func (_u *TaskFeedUpdate) SetTeammateID(v ulid.ID) *TaskFeedUpdate {
	_u.mutation.SetTeammateID(v)
	return _u
}

// SetNillableTeammateID sets the "teammate_id" field if the given value is not nil.
func (_u *TaskFeedUpdate) SetNillableTeammateID(v *ulid.ID) *TaskFeedUpdate {
	if v != nil {
		_u.SetTeammateID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskFeedUpdate) SetDescription(v map[string]interface{}) *TaskFeedUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetIsFirst sets the "is_first" field.
func (_u *TaskFeedUpdate) SetIsFirst(v bool) *TaskFeedUpdate {
	_u.mutation.SetIsFirst(v)
	return _u
}

// SetNillableIsFirst sets the "is_first" field if the given value is not nil.
func (_u *TaskFeedUpdate) SetNillableIsFirst(v *bool) *TaskFeedUpdate {
	if v != nil {
		_u.SetIsFirst(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *TaskFeedUpdate) SetIsPinned(v bool) *TaskFeedUpdate {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *TaskFeedUpdate) SetNillableIsPinned(v *bool) *TaskFeedUpdate {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskFeedUpdate) SetUpdatedAt(v time.Time) *TaskFeedUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskFeedUpdate) SetTask(v *Task) *TaskFeedUpdate {
	return _u.SetTaskID(v.ID)
}

// SetTeammate sets the "teammate" edge to the Teammate entity.
func (_u *TaskFeedUpdate) SetTeammate(v *Teammate) *TaskFeedUpdate {
	return _u.SetTeammateID(v.ID)
}

// AddTaskFeedLikeIDs adds the "taskFeedLikes" edge to the TaskFeedLike entity by IDs.
func (_u *TaskFeedUpdate) AddTaskFeedLikeIDs(ids ...ulid.ID) *TaskFeedUpdate {
	_u.mutation.AddTaskFeedLikeIDs(ids...)
	return _u
}

// AddTaskFeedLikes adds the "taskFeedLikes" edges to the TaskFeedLike entity.
func (_u *TaskFeedUpdate) AddTaskFeedLikes(v ...*TaskFeedLike) *TaskFeedUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskFeedLikeIDs(ids...)
}

// AddTaskFileIDs adds the "taskFiles" edge to the TaskFile entity by IDs.
func (_u *TaskFeedUpdate) AddTaskFileIDs(ids ...ulid.ID) *TaskFeedUpdate {
	_u.mutation.AddTaskFileIDs(ids...)
	return _u
}

// AddTaskFiles adds the "taskFiles" edges to the TaskFile entity.
func (_u *TaskFeedUpdate) AddTaskFiles(v ...*TaskFile) *TaskFeedUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskFileIDs(ids...)
}

// Mutation returns the TaskFeedMutation object of the builder.
func (_u *TaskFeedUpdate) Mutation() *TaskFeedMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskFeedUpdate) ClearTask() *TaskFeedUpdate {
	_u.mutation.ClearTask()
	return _u
}

// ClearTeammate clears the "teammate" edge to the Teammate entity.
func (_u *TaskFeedUpdate) ClearTeammate() *TaskFeedUpdate {
	_u.mutation.ClearTeammate()
	return _u
}

// ClearTaskFeedLikes clears all "taskFeedLikes" edges to the TaskFeedLike entity.
func (_u *TaskFeedUpdate) ClearTaskFeedLikes() *TaskFeedUpdate {
	_u.mutation.ClearTaskFeedLikes()
	return _u
}

// RemoveTaskFeedLikeIDs removes the "taskFeedLikes" edge to TaskFeedLike entities by IDs.
func (_u *TaskFeedUpdate) RemoveTaskFeedLikeIDs(ids ...ulid.ID) *TaskFeedUpdate {
	_u.mutation.RemoveTaskFeedLikeIDs(ids...)
	return _u
}

// RemoveTaskFeedLikes removes "taskFeedLikes" edges to TaskFeedLike entities.
func (_u *TaskFeedUpdate) RemoveTaskFeedLikes(v ...*TaskFeedLike) *TaskFeedUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskFeedLikeIDs(ids...)
}

// ClearTaskFiles clears all "taskFiles" edges to the TaskFile entity.
func (_u *TaskFeedUpdate) ClearTaskFiles() *TaskFeedUpdate {
	_u.mutation.ClearTaskFiles()
	return _u
}

// RemoveTaskFileIDs removes the "taskFiles" edge to TaskFile entities by IDs.
func (_u *TaskFeedUpdate) RemoveTaskFileIDs(ids ...ulid.ID) *TaskFeedUpdate {
	_u.mutation.RemoveTaskFileIDs(ids...)
	return _u
}

// RemoveTaskFiles removes "taskFiles" edges to TaskFile entities.
func (_u *TaskFeedUpdate) RemoveTaskFiles(v ...*TaskFile) *TaskFeedUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskFeedUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskFeedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskFeedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskFeedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskFeedUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taskfeed.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskFeedUpdate) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskFeed.task"`)
	}
	if _u.mutation.TeammateCleared() && len(_u.mutation.TeammateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskFeed.teammate"`)
	}
	return nil
}

func (_u *TaskFeedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskfeed.Table, taskfeed.Columns, sqlgraph.NewFieldSpec(taskfeed.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taskfeed.FieldDescription, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.IsFirst(); ok {
		_spec.SetField(taskfeed.FieldIsFirst, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(taskfeed.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taskfeed.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TaskTable,
			Columns: []string{taskfeed.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TaskTable,
			Columns: []string{taskfeed.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeammateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TeammateTable,
			Columns: []string{taskfeed.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeammateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TeammateTable,
			Columns: []string{taskfeed.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskFeedLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFeedLikesTable,
			Columns: []string{taskfeed.TaskFeedLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfeedlike.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskFeedLikesIDs(); len(nodes) > 0 && !_u.mutation.TaskFeedLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFeedLikesTable,
			Columns: []string{taskfeed.TaskFeedLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfeedlike.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskFeedLikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFeedLikesTable,
			Columns: []string{taskfeed.TaskFeedLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfeedlike.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFilesTable,
			Columns: []string{taskfeed.TaskFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfile.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskFilesIDs(); len(nodes) > 0 && !_u.mutation.TaskFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFilesTable,
			Columns: []string{taskfeed.TaskFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFilesTable,
			Columns: []string{taskfeed.TaskFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskfeed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskFeedUpdateOne is the builder for updating a single TaskFeed entity.
type TaskFeedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskFeedMutation
}

// SetTaskID sets the "task_id" field.
func (_u *TaskFeedUpdateOne) SetTaskID(v ulid.ID) *TaskFeedUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskFeedUpdateOne) SetNillableTaskID(v *ulid.ID) *TaskFeedUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetTeammateID sets the "teammate_id" field.
func (_u *TaskFeedUpdateOne) SetTeammateID(v ulid.ID) *TaskFeedUpdateOne {
	_u.mutation.SetTeammateID(v)
	return _u
}

// SetNillableTeammateID sets the "teammate_id" field if the given value is not nil.
func (_u *TaskFeedUpdateOne) SetNillableTeammateID(v *ulid.ID) *TaskFeedUpdateOne {
	if v != nil {
		_u.SetTeammateID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskFeedUpdateOne) SetDescription(v map[string]interface{}) *TaskFeedUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetIsFirst sets the "is_first" field.
func (_u *TaskFeedUpdateOne) SetIsFirst(v bool) *TaskFeedUpdateOne {
	_u.mutation.SetIsFirst(v)
	return _u
}

// SetNillableIsFirst sets the "is_first" field if the given value is not nil.
func (_u *TaskFeedUpdateOne) SetNillableIsFirst(v *bool) *TaskFeedUpdateOne {
	if v != nil {
		_u.SetIsFirst(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *TaskFeedUpdateOne) SetIsPinned(v bool) *TaskFeedUpdateOne {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *TaskFeedUpdateOne) SetNillableIsPinned(v *bool) *TaskFeedUpdateOne {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskFeedUpdateOne) SetUpdatedAt(v time.Time) *TaskFeedUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskFeedUpdateOne) SetTask(v *Task) *TaskFeedUpdateOne {
	return _u.SetTaskID(v.ID)
}

// SetTeammate sets the "teammate" edge to the Teammate entity.
func (_u *TaskFeedUpdateOne) SetTeammate(v *Teammate) *TaskFeedUpdateOne {
	return _u.SetTeammateID(v.ID)
}

// AddTaskFeedLikeIDs adds the "taskFeedLikes" edge to the TaskFeedLike entity by IDs.
func (_u *TaskFeedUpdateOne) AddTaskFeedLikeIDs(ids ...ulid.ID) *TaskFeedUpdateOne {
	_u.mutation.AddTaskFeedLikeIDs(ids...)
	return _u
}

// AddTaskFeedLikes adds the "taskFeedLikes" edges to the TaskFeedLike entity.
func (_u *TaskFeedUpdateOne) AddTaskFeedLikes(v ...*TaskFeedLike) *TaskFeedUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskFeedLikeIDs(ids...)
}

// AddTaskFileIDs adds the "taskFiles" edge to the TaskFile entity by IDs.
func (_u *TaskFeedUpdateOne) AddTaskFileIDs(ids ...ulid.ID) *TaskFeedUpdateOne {
	_u.mutation.AddTaskFileIDs(ids...)
	return _u
}

// AddTaskFiles adds the "taskFiles" edges to the TaskFile entity.
func (_u *TaskFeedUpdateOne) AddTaskFiles(v ...*TaskFile) *TaskFeedUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskFileIDs(ids...)
}

// Mutation returns the TaskFeedMutation object of the builder.
func (_u *TaskFeedUpdateOne) Mutation() *TaskFeedMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskFeedUpdateOne) ClearTask() *TaskFeedUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// ClearTeammate clears the "teammate" edge to the Teammate entity.
func (_u *TaskFeedUpdateOne) ClearTeammate() *TaskFeedUpdateOne {
	_u.mutation.ClearTeammate()
	return _u
}

// ClearTaskFeedLikes clears all "taskFeedLikes" edges to the TaskFeedLike entity.
func (_u *TaskFeedUpdateOne) ClearTaskFeedLikes() *TaskFeedUpdateOne {
	_u.mutation.ClearTaskFeedLikes()
	return _u
}

// RemoveTaskFeedLikeIDs removes the "taskFeedLikes" edge to TaskFeedLike entities by IDs.
func (_u *TaskFeedUpdateOne) RemoveTaskFeedLikeIDs(ids ...ulid.ID) *TaskFeedUpdateOne {
	_u.mutation.RemoveTaskFeedLikeIDs(ids...)
	return _u
}

// RemoveTaskFeedLikes removes "taskFeedLikes" edges to TaskFeedLike entities.
func (_u *TaskFeedUpdateOne) RemoveTaskFeedLikes(v ...*TaskFeedLike) *TaskFeedUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskFeedLikeIDs(ids...)
}

// ClearTaskFiles clears all "taskFiles" edges to the TaskFile entity.
func (_u *TaskFeedUpdateOne) ClearTaskFiles() *TaskFeedUpdateOne {
	_u.mutation.ClearTaskFiles()
	return _u
}

// RemoveTaskFileIDs removes the "taskFiles" edge to TaskFile entities by IDs.
func (_u *TaskFeedUpdateOne) RemoveTaskFileIDs(ids ...ulid.ID) *TaskFeedUpdateOne {
	_u.mutation.RemoveTaskFileIDs(ids...)
	return _u
}

// RemoveTaskFiles removes "taskFiles" edges to TaskFile entities.
func (_u *TaskFeedUpdateOne) RemoveTaskFiles(v ...*TaskFile) *TaskFeedUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskFileIDs(ids...)
}

// Where appends a list predicates to the TaskFeedUpdate builder.
func (_u *TaskFeedUpdateOne) Where(ps ...predicate.TaskFeed) *TaskFeedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskFeedUpdateOne) Select(field string, fields ...string) *TaskFeedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskFeed entity.
func (_u *TaskFeedUpdateOne) Save(ctx context.Context) (*TaskFeed, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskFeedUpdateOne) SaveX(ctx context.Context) *TaskFeed {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskFeedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskFeedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskFeedUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taskfeed.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskFeedUpdateOne) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskFeed.task"`)
	}
	if _u.mutation.TeammateCleared() && len(_u.mutation.TeammateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskFeed.teammate"`)
	}
	return nil
}

func (_u *TaskFeedUpdateOne) sqlSave(ctx context.Context) (_node *TaskFeed, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskfeed.Table, taskfeed.Columns, sqlgraph.NewFieldSpec(taskfeed.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskFeed.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskfeed.FieldID)
		for _, f := range fields {
			if !taskfeed.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskfeed.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taskfeed.FieldDescription, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.IsFirst(); ok {
		_spec.SetField(taskfeed.FieldIsFirst, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(taskfeed.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taskfeed.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TaskTable,
			Columns: []string{taskfeed.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TaskTable,
			Columns: []string{taskfeed.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeammateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TeammateTable,
			Columns: []string{taskfeed.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeammateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskfeed.TeammateTable,
			Columns: []string{taskfeed.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskFeedLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFeedLikesTable,
			Columns: []string{taskfeed.TaskFeedLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfeedlike.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskFeedLikesIDs(); len(nodes) > 0 && !_u.mutation.TaskFeedLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFeedLikesTable,
			Columns: []string{taskfeed.TaskFeedLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfeedlike.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskFeedLikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFeedLikesTable,
			Columns: []string{taskfeed.TaskFeedLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfeedlike.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFilesTable,
			Columns: []string{taskfeed.TaskFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfile.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskFilesIDs(); len(nodes) > 0 && !_u.mutation.TaskFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFilesTable,
			Columns: []string{taskfeed.TaskFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskfeed.TaskFilesTable,
			Columns: []string{taskfeed.TaskFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskFeed{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskfeed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
