// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/predicate"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/ent/testtodo"
	"asana-clone-app/ent/testuser"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestTodoUpdate is the builder for updating TestTodo entities.
type TestTodoUpdate struct {
	config
	hooks    []Hook
	mutation *TestTodoMutation
}

// Where appends a list predicates to the TestTodoUpdate builder.
func (_u *TestTodoUpdate) Where(ps ...predicate.TestTodo) *TestTodoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTestUserID sets the "test_user_id" field.
func (_u *TestTodoUpdate) SetTestUserID(v ulid.ID) *TestTodoUpdate {
	_u.mutation.SetTestUserID(v)
	return _u
}

// SetNillableTestUserID sets the "test_user_id" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableTestUserID(v *ulid.ID) *TestTodoUpdate {
	if v != nil {
		_u.SetTestUserID(*v)
	}
	return _u
}

// ClearTestUserID clears the value of the "test_user_id" field.
func (_u *TestTodoUpdate) ClearTestUserID() *TestTodoUpdate {
	_u.mutation.ClearTestUserID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TestTodoUpdate) SetCreatedBy(v ulid.ID) *TestTodoUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableCreatedBy(v *ulid.ID) *TestTodoUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetParentTodoID sets the "parent_todo_id" field.
func (_u *TestTodoUpdate) SetParentTodoID(v ulid.ID) *TestTodoUpdate {
	_u.mutation.SetParentTodoID(v)
	return _u
}

// SetNillableParentTodoID sets the "parent_todo_id" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableParentTodoID(v *ulid.ID) *TestTodoUpdate {
	if v != nil {
		_u.SetParentTodoID(*v)
	}
	return _u
}

// ClearParentTodoID clears the value of the "parent_todo_id" field.
func (_u *TestTodoUpdate) ClearParentTodoID() *TestTodoUpdate {
	_u.mutation.ClearParentTodoID()
	return _u
}

// SetName sets the "name" field.
func (_u *TestTodoUpdate) SetName(v string) *TestTodoUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableName(v *string) *TestTodoUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TestTodoUpdate) SetStatus(v testtodo.Status) *TestTodoUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableStatus(v *testtodo.Status) *TestTodoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TestTodoUpdate) SetPriority(v int) *TestTodoUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillablePriority(v *int) *TestTodoUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TestTodoUpdate) AddPriority(v int) *TestTodoUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TestTodoUpdate) SetDueDate(v time.Time) *TestTodoUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableDueDate(v *time.Time) *TestTodoUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TestTodoUpdate) ClearDueDate() *TestTodoUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TestTodoUpdate) SetUpdatedAt(v time.Time) *TestTodoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTestUser sets the "testUser" edge to the TestUser entity.
func (_u *TestTodoUpdate) SetTestUser(v *TestUser) *TestTodoUpdate {
	return _u.SetTestUserID(v.ID)
}

// SetParentID sets the "parent" edge to the TestTodo entity by ID.
func (_u *TestTodoUpdate) SetParentID(id ulid.ID) *TestTodoUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the TestTodo entity by ID if the given value is not nil.
func (_u *TestTodoUpdate) SetNillableParentID(id *ulid.ID) *TestTodoUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the TestTodo entity.
func (_u *TestTodoUpdate) SetParent(v *TestTodo) *TestTodoUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the TestTodo entity by IDs.
func (_u *TestTodoUpdate) AddChildIDs(ids ...ulid.ID) *TestTodoUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the TestTodo entity.
func (_u *TestTodoUpdate) AddChildren(v ...*TestTodo) *TestTodoUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the TestTodoMutation object of the builder.
func (_u *TestTodoUpdate) Mutation() *TestTodoMutation {
	return _u.mutation
}

// ClearTestUser clears the "testUser" edge to the TestUser entity.
func (_u *TestTodoUpdate) ClearTestUser() *TestTodoUpdate {
	_u.mutation.ClearTestUser()
	return _u
}

// ClearParent clears the "parent" edge to the TestTodo entity.
func (_u *TestTodoUpdate) ClearParent() *TestTodoUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the TestTodo entity.
func (_u *TestTodoUpdate) ClearChildren() *TestTodoUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to TestTodo entities by IDs.
func (_u *TestTodoUpdate) RemoveChildIDs(ids ...ulid.ID) *TestTodoUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to TestTodo entities.
func (_u *TestTodoUpdate) RemoveChildren(v ...*TestTodo) *TestTodoUpdate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TestTodoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestTodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TestTodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestTodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TestTodoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := testtodo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestTodoUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := testtodo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TestTodo.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TestTodoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testtodo.Table, testtodo.Columns, sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(testtodo.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(testtodo.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(testtodo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(testtodo.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(testtodo.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(testtodo.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(testtodo.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(testtodo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TestUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.TestUserTable,
			Columns: []string{testtodo.TestUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TestUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.TestUserTable,
			Columns: []string{testtodo.TestUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.ParentTable,
			Columns: []string{testtodo.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.ParentTable,
			Columns: []string{testtodo.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   testtodo.ChildrenTable,
			Columns: []string{testtodo.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   testtodo.ChildrenTable,
			Columns: []string{testtodo.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   testtodo.ChildrenTable,
			Columns: []string{testtodo.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testtodo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TestTodoUpdateOne is the builder for updating a single TestTodo entity.
type TestTodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestTodoMutation
}

// SetTestUserID sets the "test_user_id" field.
func (_u *TestTodoUpdateOne) SetTestUserID(v ulid.ID) *TestTodoUpdateOne {
	_u.mutation.SetTestUserID(v)
	return _u
}

// SetNillableTestUserID sets the "test_user_id" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableTestUserID(v *ulid.ID) *TestTodoUpdateOne {
	if v != nil {
		_u.SetTestUserID(*v)
	}
	return _u
}

// ClearTestUserID clears the value of the "test_user_id" field.
func (_u *TestTodoUpdateOne) ClearTestUserID() *TestTodoUpdateOne {
	_u.mutation.ClearTestUserID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TestTodoUpdateOne) SetCreatedBy(v ulid.ID) *TestTodoUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableCreatedBy(v *ulid.ID) *TestTodoUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetParentTodoID sets the "parent_todo_id" field.
func (_u *TestTodoUpdateOne) SetParentTodoID(v ulid.ID) *TestTodoUpdateOne {
	_u.mutation.SetParentTodoID(v)
	return _u
}

// SetNillableParentTodoID sets the "parent_todo_id" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableParentTodoID(v *ulid.ID) *TestTodoUpdateOne {
	if v != nil {
		_u.SetParentTodoID(*v)
	}
	return _u
}

// ClearParentTodoID clears the value of the "parent_todo_id" field.
func (_u *TestTodoUpdateOne) ClearParentTodoID() *TestTodoUpdateOne {
	_u.mutation.ClearParentTodoID()
	return _u
}

// SetName sets the "name" field.
func (_u *TestTodoUpdateOne) SetName(v string) *TestTodoUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableName(v *string) *TestTodoUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TestTodoUpdateOne) SetStatus(v testtodo.Status) *TestTodoUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableStatus(v *testtodo.Status) *TestTodoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TestTodoUpdateOne) SetPriority(v int) *TestTodoUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillablePriority(v *int) *TestTodoUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TestTodoUpdateOne) AddPriority(v int) *TestTodoUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TestTodoUpdateOne) SetDueDate(v time.Time) *TestTodoUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableDueDate(v *time.Time) *TestTodoUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TestTodoUpdateOne) ClearDueDate() *TestTodoUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TestTodoUpdateOne) SetUpdatedAt(v time.Time) *TestTodoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTestUser sets the "testUser" edge to the TestUser entity.
func (_u *TestTodoUpdateOne) SetTestUser(v *TestUser) *TestTodoUpdateOne {
	return _u.SetTestUserID(v.ID)
}

// SetParentID sets the "parent" edge to the TestTodo entity by ID.
func (_u *TestTodoUpdateOne) SetParentID(id ulid.ID) *TestTodoUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the TestTodo entity by ID if the given value is not nil.
func (_u *TestTodoUpdateOne) SetNillableParentID(id *ulid.ID) *TestTodoUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the TestTodo entity.
func (_u *TestTodoUpdateOne) SetParent(v *TestTodo) *TestTodoUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the TestTodo entity by IDs.
func (_u *TestTodoUpdateOne) AddChildIDs(ids ...ulid.ID) *TestTodoUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the TestTodo entity.
func (_u *TestTodoUpdateOne) AddChildren(v ...*TestTodo) *TestTodoUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the TestTodoMutation object of the builder.
func (_u *TestTodoUpdateOne) Mutation() *TestTodoMutation {
	return _u.mutation
}

// ClearTestUser clears the "testUser" edge to the TestUser entity.
func (_u *TestTodoUpdateOne) ClearTestUser() *TestTodoUpdateOne {
	_u.mutation.ClearTestUser()
	return _u
}

// ClearParent clears the "parent" edge to the TestTodo entity.
func (_u *TestTodoUpdateOne) ClearParent() *TestTodoUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the TestTodo entity.
func (_u *TestTodoUpdateOne) ClearChildren() *TestTodoUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to TestTodo entities by IDs.
func (_u *TestTodoUpdateOne) RemoveChildIDs(ids ...ulid.ID) *TestTodoUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to TestTodo entities.
func (_u *TestTodoUpdateOne) RemoveChildren(v ...*TestTodo) *TestTodoUpdateOne {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the TestTodoUpdate builder.
func (_u *TestTodoUpdateOne) Where(ps ...predicate.TestTodo) *TestTodoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TestTodoUpdateOne) Select(field string, fields ...string) *TestTodoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TestTodo entity.
func (_u *TestTodoUpdateOne) Save(ctx context.Context) (*TestTodo, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestTodoUpdateOne) SaveX(ctx context.Context) *TestTodo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TestTodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestTodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TestTodoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := testtodo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestTodoUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := testtodo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TestTodo.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TestTodoUpdateOne) sqlSave(ctx context.Context) (_node *TestTodo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testtodo.Table, testtodo.Columns, sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TestTodo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testtodo.FieldID)
		for _, f := range fields {
			if !testtodo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testtodo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(testtodo.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(testtodo.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(testtodo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(testtodo.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(testtodo.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(testtodo.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(testtodo.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(testtodo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TestUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.TestUserTable,
			Columns: []string{testtodo.TestUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TestUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.TestUserTable,
			Columns: []string{testtodo.TestUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.ParentTable,
			Columns: []string{testtodo.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testtodo.ParentTable,
			Columns: []string{testtodo.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   testtodo.ChildrenTable,
			Columns: []string{testtodo.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   testtodo.ChildrenTable,
			Columns: []string{testtodo.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   testtodo.ChildrenTable,
			Columns: []string{testtodo.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testtodo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TestTodo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testtodo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
