// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/activitytype"
	"asana-clone-app/ent/predicate"
	"asana-clone-app/ent/project"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/ent/teammate"
	"asana-clone-app/ent/workspace"
	"asana-clone-app/ent/workspaceactivity"
	"asana-clone-app/ent/workspaceactivitytask"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceActivityQuery is the builder for querying WorkspaceActivity entities.
type WorkspaceActivityQuery struct {
	config
	ctx                             *QueryContext
	order                           []workspaceactivity.OrderOption
	inters                          []Interceptor
	predicates                      []predicate.WorkspaceActivity
	withActivityType                *ActivityTypeQuery
	withWorkspace                   *WorkspaceQuery
	withProject                     *ProjectQuery
	withTeammate                    *TeammateQuery
	withWorkspaceActivityTasks      *WorkspaceActivityTaskQuery
	modifiers                       []func(*sql.Selector)
	loadTotal                       []func(context.Context, []*WorkspaceActivity) error
	withNamedWorkspaceActivityTasks map[string]*WorkspaceActivityTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkspaceActivityQuery builder.
func (_q *WorkspaceActivityQuery) Where(ps ...predicate.WorkspaceActivity) *WorkspaceActivityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WorkspaceActivityQuery) Limit(limit int) *WorkspaceActivityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WorkspaceActivityQuery) Offset(offset int) *WorkspaceActivityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WorkspaceActivityQuery) Unique(unique bool) *WorkspaceActivityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WorkspaceActivityQuery) Order(o ...workspaceactivity.OrderOption) *WorkspaceActivityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryActivityType chains the current query on the "activityType" edge.
func (_q *WorkspaceActivityQuery) QueryActivityType() *ActivityTypeQuery {
	query := (&ActivityTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workspaceactivity.Table, workspaceactivity.FieldID, selector),
			sqlgraph.To(activitytype.Table, activitytype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workspaceactivity.ActivityTypeTable, workspaceactivity.ActivityTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkspace chains the current query on the "workspace" edge.
func (_q *WorkspaceActivityQuery) QueryWorkspace() *WorkspaceQuery {
	query := (&WorkspaceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workspaceactivity.Table, workspaceactivity.FieldID, selector),
			sqlgraph.To(workspace.Table, workspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workspaceactivity.WorkspaceTable, workspaceactivity.WorkspaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *WorkspaceActivityQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workspaceactivity.Table, workspaceactivity.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workspaceactivity.ProjectTable, workspaceactivity.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeammate chains the current query on the "teammate" edge.
func (_q *WorkspaceActivityQuery) QueryTeammate() *TeammateQuery {
	query := (&TeammateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workspaceactivity.Table, workspaceactivity.FieldID, selector),
			sqlgraph.To(teammate.Table, teammate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workspaceactivity.TeammateTable, workspaceactivity.TeammateColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkspaceActivityTasks chains the current query on the "workspaceActivityTasks" edge.
func (_q *WorkspaceActivityQuery) QueryWorkspaceActivityTasks() *WorkspaceActivityTaskQuery {
	query := (&WorkspaceActivityTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workspaceactivity.Table, workspaceactivity.FieldID, selector),
			sqlgraph.To(workspaceactivitytask.Table, workspaceactivitytask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workspaceactivity.WorkspaceActivityTasksTable, workspaceactivity.WorkspaceActivityTasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorkspaceActivity entity from the query.
// Returns a *NotFoundError when no WorkspaceActivity was found.
func (_q *WorkspaceActivityQuery) First(ctx context.Context) (*WorkspaceActivity, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workspaceactivity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) FirstX(ctx context.Context) *WorkspaceActivity {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkspaceActivity ID from the query.
// Returns a *NotFoundError when no WorkspaceActivity ID was found.
func (_q *WorkspaceActivityQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workspaceactivity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkspaceActivity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkspaceActivity entity is found.
// Returns a *NotFoundError when no WorkspaceActivity entities are found.
func (_q *WorkspaceActivityQuery) Only(ctx context.Context) (*WorkspaceActivity, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workspaceactivity.Label}
	default:
		return nil, &NotSingularError{workspaceactivity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) OnlyX(ctx context.Context) *WorkspaceActivity {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkspaceActivity ID in the query.
// Returns a *NotSingularError when more than one WorkspaceActivity ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WorkspaceActivityQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workspaceactivity.Label}
	default:
		err = &NotSingularError{workspaceactivity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkspaceActivities.
func (_q *WorkspaceActivityQuery) All(ctx context.Context) ([]*WorkspaceActivity, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkspaceActivity, *WorkspaceActivityQuery]()
	return withInterceptors[[]*WorkspaceActivity](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) AllX(ctx context.Context) []*WorkspaceActivity {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkspaceActivity IDs.
func (_q *WorkspaceActivityQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(workspaceactivity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WorkspaceActivityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WorkspaceActivityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WorkspaceActivityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WorkspaceActivityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkspaceActivityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WorkspaceActivityQuery) Clone() *WorkspaceActivityQuery {
	if _q == nil {
		return nil
	}
	return &WorkspaceActivityQuery{
		config:                     _q.config,
		ctx:                        _q.ctx.Clone(),
		order:                      append([]workspaceactivity.OrderOption{}, _q.order...),
		inters:                     append([]Interceptor{}, _q.inters...),
		predicates:                 append([]predicate.WorkspaceActivity{}, _q.predicates...),
		withActivityType:           _q.withActivityType.Clone(),
		withWorkspace:              _q.withWorkspace.Clone(),
		withProject:                _q.withProject.Clone(),
		withTeammate:               _q.withTeammate.Clone(),
		withWorkspaceActivityTasks: _q.withWorkspaceActivityTasks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithActivityType tells the query-builder to eager-load the nodes that are connected to
// the "activityType" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkspaceActivityQuery) WithActivityType(opts ...func(*ActivityTypeQuery)) *WorkspaceActivityQuery {
	query := (&ActivityTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActivityType = query
	return _q
}

// WithWorkspace tells the query-builder to eager-load the nodes that are connected to
// the "workspace" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkspaceActivityQuery) WithWorkspace(opts ...func(*WorkspaceQuery)) *WorkspaceActivityQuery {
	query := (&WorkspaceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkspace = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkspaceActivityQuery) WithProject(opts ...func(*ProjectQuery)) *WorkspaceActivityQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithTeammate tells the query-builder to eager-load the nodes that are connected to
// the "teammate" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkspaceActivityQuery) WithTeammate(opts ...func(*TeammateQuery)) *WorkspaceActivityQuery {
	query := (&TeammateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeammate = query
	return _q
}

// WithWorkspaceActivityTasks tells the query-builder to eager-load the nodes that are connected to
// the "workspaceActivityTasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkspaceActivityQuery) WithWorkspaceActivityTasks(opts ...func(*WorkspaceActivityTaskQuery)) *WorkspaceActivityQuery {
	query := (&WorkspaceActivityTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkspaceActivityTasks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ActivityTypeID ulid.ID `json:"activity_type_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkspaceActivity.Query().
//		GroupBy(workspaceactivity.FieldActivityTypeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WorkspaceActivityQuery) GroupBy(field string, fields ...string) *WorkspaceActivityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkspaceActivityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = workspaceactivity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ActivityTypeID ulid.ID `json:"activity_type_id,omitempty"`
//	}
//
//	client.WorkspaceActivity.Query().
//		Select(workspaceactivity.FieldActivityTypeID).
//		Scan(ctx, &v)
func (_q *WorkspaceActivityQuery) Select(fields ...string) *WorkspaceActivitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WorkspaceActivitySelect{WorkspaceActivityQuery: _q}
	sbuild.label = workspaceactivity.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkspaceActivitySelect configured with the given aggregations.
func (_q *WorkspaceActivityQuery) Aggregate(fns ...AggregateFunc) *WorkspaceActivitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WorkspaceActivityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !workspaceactivity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WorkspaceActivityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkspaceActivity, error) {
	var (
		nodes       = []*WorkspaceActivity{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withActivityType != nil,
			_q.withWorkspace != nil,
			_q.withProject != nil,
			_q.withTeammate != nil,
			_q.withWorkspaceActivityTasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkspaceActivity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkspaceActivity{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withActivityType; query != nil {
		if err := _q.loadActivityType(ctx, query, nodes, nil,
			func(n *WorkspaceActivity, e *ActivityType) { n.Edges.ActivityType = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWorkspace; query != nil {
		if err := _q.loadWorkspace(ctx, query, nodes, nil,
			func(n *WorkspaceActivity, e *Workspace) { n.Edges.Workspace = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *WorkspaceActivity, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeammate; query != nil {
		if err := _q.loadTeammate(ctx, query, nodes, nil,
			func(n *WorkspaceActivity, e *Teammate) { n.Edges.Teammate = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWorkspaceActivityTasks; query != nil {
		if err := _q.loadWorkspaceActivityTasks(ctx, query, nodes,
			func(n *WorkspaceActivity) { n.Edges.WorkspaceActivityTasks = []*WorkspaceActivityTask{} },
			func(n *WorkspaceActivity, e *WorkspaceActivityTask) {
				n.Edges.WorkspaceActivityTasks = append(n.Edges.WorkspaceActivityTasks, e)
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedWorkspaceActivityTasks {
		if err := _q.loadWorkspaceActivityTasks(ctx, query, nodes,
			func(n *WorkspaceActivity) { n.appendNamedWorkspaceActivityTasks(name) },
			func(n *WorkspaceActivity, e *WorkspaceActivityTask) { n.appendNamedWorkspaceActivityTasks(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WorkspaceActivityQuery) loadActivityType(ctx context.Context, query *ActivityTypeQuery, nodes []*WorkspaceActivity, init func(*WorkspaceActivity), assign func(*WorkspaceActivity, *ActivityType)) error {
	ids := make([]ulid.ID, 0, len(nodes))
	nodeids := make(map[ulid.ID][]*WorkspaceActivity)
	for i := range nodes {
		fk := nodes[i].ActivityTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(activitytype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "activity_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WorkspaceActivityQuery) loadWorkspace(ctx context.Context, query *WorkspaceQuery, nodes []*WorkspaceActivity, init func(*WorkspaceActivity), assign func(*WorkspaceActivity, *Workspace)) error {
	ids := make([]ulid.ID, 0, len(nodes))
	nodeids := make(map[ulid.ID][]*WorkspaceActivity)
	for i := range nodes {
		fk := nodes[i].WorkspaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workspace_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WorkspaceActivityQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*WorkspaceActivity, init func(*WorkspaceActivity), assign func(*WorkspaceActivity, *Project)) error {
	ids := make([]ulid.ID, 0, len(nodes))
	nodeids := make(map[ulid.ID][]*WorkspaceActivity)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WorkspaceActivityQuery) loadTeammate(ctx context.Context, query *TeammateQuery, nodes []*WorkspaceActivity, init func(*WorkspaceActivity), assign func(*WorkspaceActivity, *Teammate)) error {
	ids := make([]ulid.ID, 0, len(nodes))
	nodeids := make(map[ulid.ID][]*WorkspaceActivity)
	for i := range nodes {
		fk := nodes[i].TeammateID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(teammate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "teammate_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WorkspaceActivityQuery) loadWorkspaceActivityTasks(ctx context.Context, query *WorkspaceActivityTaskQuery, nodes []*WorkspaceActivity, init func(*WorkspaceActivity), assign func(*WorkspaceActivity, *WorkspaceActivityTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[ulid.ID]*WorkspaceActivity)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(workspaceactivitytask.FieldWorkspaceActivityID)
	}
	query.Where(predicate.WorkspaceActivityTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workspaceactivity.WorkspaceActivityTasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkspaceActivityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workspace_activity_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *WorkspaceActivityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WorkspaceActivityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workspaceactivity.Table, workspaceactivity.Columns, sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspaceactivity.FieldID)
		for i := range fields {
			if fields[i] != workspaceactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withActivityType != nil {
			_spec.Node.AddColumnOnce(workspaceactivity.FieldActivityTypeID)
		}
		if _q.withWorkspace != nil {
			_spec.Node.AddColumnOnce(workspaceactivity.FieldWorkspaceID)
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(workspaceactivity.FieldProjectID)
		}
		if _q.withTeammate != nil {
			_spec.Node.AddColumnOnce(workspaceactivity.FieldTeammateID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WorkspaceActivityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(workspaceactivity.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = workspaceactivity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedWorkspaceActivityTasks tells the query-builder to eager-load the nodes that are connected to the "workspaceActivityTasks"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkspaceActivityQuery) WithNamedWorkspaceActivityTasks(name string, opts ...func(*WorkspaceActivityTaskQuery)) *WorkspaceActivityQuery {
	query := (&WorkspaceActivityTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedWorkspaceActivityTasks == nil {
		_q.withNamedWorkspaceActivityTasks = make(map[string]*WorkspaceActivityTaskQuery)
	}
	_q.withNamedWorkspaceActivityTasks[name] = query
	return _q
}

// WorkspaceActivityGroupBy is the group-by builder for WorkspaceActivity entities.
type WorkspaceActivityGroupBy struct {
	selector
	build *WorkspaceActivityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WorkspaceActivityGroupBy) Aggregate(fns ...AggregateFunc) *WorkspaceActivityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WorkspaceActivityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkspaceActivityQuery, *WorkspaceActivityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WorkspaceActivityGroupBy) sqlScan(ctx context.Context, root *WorkspaceActivityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkspaceActivitySelect is the builder for selecting fields of WorkspaceActivity entities.
type WorkspaceActivitySelect struct {
	*WorkspaceActivityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WorkspaceActivitySelect) Aggregate(fns ...AggregateFunc) *WorkspaceActivitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WorkspaceActivitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkspaceActivityQuery, *WorkspaceActivitySelect](ctx, _s.WorkspaceActivityQuery, _s, _s.inters, v)
}

func (_s *WorkspaceActivitySelect) sqlScan(ctx context.Context, root *WorkspaceActivityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
