// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/teammate"
	"project-management-demo-backend/ent/workspace"
	"project-management-demo-backend/ent/workspaceteammate"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceTeammateCreate is the builder for creating a WorkspaceTeammate entity.
type WorkspaceTeammateCreate struct {
	config
	mutation *WorkspaceTeammateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *WorkspaceTeammateCreate) SetWorkspaceID(v ulid.ID) *WorkspaceTeammateCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetTeammateID sets the "teammate_id" field.
func (_c *WorkspaceTeammateCreate) SetTeammateID(v ulid.ID) *WorkspaceTeammateCreate {
	_c.mutation.SetTeammateID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *WorkspaceTeammateCreate) SetRole(v string) *WorkspaceTeammateCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetIsOwner sets the "is_owner" field.
func (_c *WorkspaceTeammateCreate) SetIsOwner(v bool) *WorkspaceTeammateCreate {
	_c.mutation.SetIsOwner(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceTeammateCreate) SetCreatedAt(v time.Time) *WorkspaceTeammateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceTeammateCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceTeammateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceTeammateCreate) SetUpdatedAt(v time.Time) *WorkspaceTeammateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceTeammateCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceTeammateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkspaceTeammateCreate) SetID(v ulid.ID) *WorkspaceTeammateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkspaceTeammateCreate) SetNillableID(v *ulid.ID) *WorkspaceTeammateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *WorkspaceTeammateCreate) SetWorkspace(v *Workspace) *WorkspaceTeammateCreate {
	return _c.SetWorkspaceID(v.ID)
}

// SetTeammate sets the "teammate" edge to the Teammate entity.
func (_c *WorkspaceTeammateCreate) SetTeammate(v *Teammate) *WorkspaceTeammateCreate {
	return _c.SetTeammateID(v.ID)
}

// Mutation returns the WorkspaceTeammateMutation object of the builder.
func (_c *WorkspaceTeammateCreate) Mutation() *WorkspaceTeammateMutation {
	return _c.mutation
}

// Save creates the WorkspaceTeammate in the database.
func (_c *WorkspaceTeammateCreate) Save(ctx context.Context) (*WorkspaceTeammate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceTeammateCreate) SaveX(ctx context.Context) *WorkspaceTeammate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceTeammateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceTeammateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceTeammateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspaceteammate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspaceteammate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := workspaceteammate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceTeammateCreate) check() error {
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WorkspaceTeammate.workspace_id"`)}
	}
	if _, ok := _c.mutation.TeammateID(); !ok {
		return &ValidationError{Name: "teammate_id", err: errors.New(`ent: missing required field "WorkspaceTeammate.teammate_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "WorkspaceTeammate.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := workspaceteammate.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "WorkspaceTeammate.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsOwner(); !ok {
		return &ValidationError{Name: "is_owner", err: errors.New(`ent: missing required field "WorkspaceTeammate.is_owner"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkspaceTeammate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkspaceTeammate.updated_at"`)}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "WorkspaceTeammate.workspace"`)}
	}
	if len(_c.mutation.TeammateIDs()) == 0 {
		return &ValidationError{Name: "teammate", err: errors.New(`ent: missing required edge "WorkspaceTeammate.teammate"`)}
	}
	return nil
}

func (_c *WorkspaceTeammateCreate) sqlSave(ctx context.Context) (*WorkspaceTeammate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceTeammateCreate) createSpec() (*WorkspaceTeammate, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkspaceTeammate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspaceteammate.Table, sqlgraph.NewFieldSpec(workspaceteammate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(workspaceteammate.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.IsOwner(); ok {
		_spec.SetField(workspaceteammate.FieldIsOwner, field.TypeBool, value)
		_node.IsOwner = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspaceteammate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspaceteammate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspaceteammate.WorkspaceTable,
			Columns: []string{workspaceteammate.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeammateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspaceteammate.TeammateTable,
			Columns: []string{workspaceteammate.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeammateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceTeammate.Create().
//		SetWorkspaceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceTeammateUpsert) {
//			SetWorkspaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceTeammateCreate) OnConflict(opts ...sql.ConflictOption) *WorkspaceTeammateUpsertOne {
	_c.conflict = opts
	return &WorkspaceTeammateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceTeammate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceTeammateCreate) OnConflictColumns(columns ...string) *WorkspaceTeammateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceTeammateUpsertOne{
		create: _c,
	}
}

type (
	// WorkspaceTeammateUpsertOne is the builder for "upsert"-ing
	//  one WorkspaceTeammate node.
	WorkspaceTeammateUpsertOne struct {
		create *WorkspaceTeammateCreate
	}

	// WorkspaceTeammateUpsert is the "OnConflict" setter.
	WorkspaceTeammateUpsert struct {
		*sql.UpdateSet
	}
)

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceTeammateUpsert) SetWorkspaceID(v ulid.ID) *WorkspaceTeammateUpsert {
	u.Set(workspaceteammate.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsert) UpdateWorkspaceID() *WorkspaceTeammateUpsert {
	u.SetExcluded(workspaceteammate.FieldWorkspaceID)
	return u
}

// SetTeammateID sets the "teammate_id" field.
func (u *WorkspaceTeammateUpsert) SetTeammateID(v ulid.ID) *WorkspaceTeammateUpsert {
	u.Set(workspaceteammate.FieldTeammateID, v)
	return u
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsert) UpdateTeammateID() *WorkspaceTeammateUpsert {
	u.SetExcluded(workspaceteammate.FieldTeammateID)
	return u
}

// SetRole sets the "role" field.
func (u *WorkspaceTeammateUpsert) SetRole(v string) *WorkspaceTeammateUpsert {
	u.Set(workspaceteammate.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsert) UpdateRole() *WorkspaceTeammateUpsert {
	u.SetExcluded(workspaceteammate.FieldRole)
	return u
}

// SetIsOwner sets the "is_owner" field.
func (u *WorkspaceTeammateUpsert) SetIsOwner(v bool) *WorkspaceTeammateUpsert {
	u.Set(workspaceteammate.FieldIsOwner, v)
	return u
}

// UpdateIsOwner sets the "is_owner" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsert) UpdateIsOwner() *WorkspaceTeammateUpsert {
	u.SetExcluded(workspaceteammate.FieldIsOwner)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceTeammateUpsert) SetUpdatedAt(v time.Time) *WorkspaceTeammateUpsert {
	u.Set(workspaceteammate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsert) UpdateUpdatedAt() *WorkspaceTeammateUpsert {
	u.SetExcluded(workspaceteammate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.WorkspaceTeammate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workspaceteammate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkspaceTeammateUpsertOne) UpdateNewValues() *WorkspaceTeammateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(workspaceteammate.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(workspaceteammate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceTeammate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkspaceTeammateUpsertOne) Ignore() *WorkspaceTeammateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceTeammateUpsertOne) DoNothing() *WorkspaceTeammateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceTeammateCreate.OnConflict
// documentation for more info.
func (u *WorkspaceTeammateUpsertOne) Update(set func(*WorkspaceTeammateUpsert)) *WorkspaceTeammateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceTeammateUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceTeammateUpsertOne) SetWorkspaceID(v ulid.ID) *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertOne) UpdateWorkspaceID() *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetTeammateID sets the "teammate_id" field.
func (u *WorkspaceTeammateUpsertOne) SetTeammateID(v ulid.ID) *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetTeammateID(v)
	})
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertOne) UpdateTeammateID() *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateTeammateID()
	})
}

// SetRole sets the "role" field.
func (u *WorkspaceTeammateUpsertOne) SetRole(v string) *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertOne) UpdateRole() *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateRole()
	})
}

// SetIsOwner sets the "is_owner" field.
func (u *WorkspaceTeammateUpsertOne) SetIsOwner(v bool) *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetIsOwner(v)
	})
}

// UpdateIsOwner sets the "is_owner" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertOne) UpdateIsOwner() *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateIsOwner()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceTeammateUpsertOne) SetUpdatedAt(v time.Time) *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertOne) UpdateUpdatedAt() *WorkspaceTeammateUpsertOne {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceTeammateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceTeammateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceTeammateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkspaceTeammateUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WorkspaceTeammateUpsertOne.ID is not supported by MySQL driver. Use WorkspaceTeammateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkspaceTeammateUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkspaceTeammateCreateBulk is the builder for creating many WorkspaceTeammate entities in bulk.
type WorkspaceTeammateCreateBulk struct {
	config
	err      error
	builders []*WorkspaceTeammateCreate
	conflict []sql.ConflictOption
}

// Save creates the WorkspaceTeammate entities in the database.
func (_c *WorkspaceTeammateCreateBulk) Save(ctx context.Context) ([]*WorkspaceTeammate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkspaceTeammate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceTeammateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceTeammateCreateBulk) SaveX(ctx context.Context) []*WorkspaceTeammate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceTeammateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceTeammateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceTeammate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceTeammateUpsert) {
//			SetWorkspaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceTeammateCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkspaceTeammateUpsertBulk {
	_c.conflict = opts
	return &WorkspaceTeammateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceTeammate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceTeammateCreateBulk) OnConflictColumns(columns ...string) *WorkspaceTeammateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceTeammateUpsertBulk{
		create: _c,
	}
}

// WorkspaceTeammateUpsertBulk is the builder for "upsert"-ing
// a bulk of WorkspaceTeammate nodes.
type WorkspaceTeammateUpsertBulk struct {
	create *WorkspaceTeammateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WorkspaceTeammate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workspaceteammate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkspaceTeammateUpsertBulk) UpdateNewValues() *WorkspaceTeammateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(workspaceteammate.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(workspaceteammate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceTeammate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkspaceTeammateUpsertBulk) Ignore() *WorkspaceTeammateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceTeammateUpsertBulk) DoNothing() *WorkspaceTeammateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceTeammateCreateBulk.OnConflict
// documentation for more info.
func (u *WorkspaceTeammateUpsertBulk) Update(set func(*WorkspaceTeammateUpsert)) *WorkspaceTeammateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceTeammateUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceTeammateUpsertBulk) SetWorkspaceID(v ulid.ID) *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertBulk) UpdateWorkspaceID() *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetTeammateID sets the "teammate_id" field.
func (u *WorkspaceTeammateUpsertBulk) SetTeammateID(v ulid.ID) *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetTeammateID(v)
	})
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertBulk) UpdateTeammateID() *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateTeammateID()
	})
}

// SetRole sets the "role" field.
func (u *WorkspaceTeammateUpsertBulk) SetRole(v string) *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertBulk) UpdateRole() *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateRole()
	})
}

// SetIsOwner sets the "is_owner" field.
func (u *WorkspaceTeammateUpsertBulk) SetIsOwner(v bool) *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetIsOwner(v)
	})
}

// UpdateIsOwner sets the "is_owner" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertBulk) UpdateIsOwner() *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateIsOwner()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceTeammateUpsertBulk) SetUpdatedAt(v time.Time) *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceTeammateUpsertBulk) UpdateUpdatedAt() *WorkspaceTeammateUpsertBulk {
	return u.Update(func(s *WorkspaceTeammateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceTeammateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkspaceTeammateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceTeammateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceTeammateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
