// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/archivedtaskactivity"
	"asana-clone-app/ent/archivedworkspaceactivity"
	"asana-clone-app/ent/deletedtask"
	"asana-clone-app/ent/deletedteammatetask"
	"asana-clone-app/ent/favoriteworkspace"
	"asana-clone-app/ent/project"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/ent/tag"
	"asana-clone-app/ent/taskactivity"
	"asana-clone-app/ent/tasklike"
	"asana-clone-app/ent/teammate"
	"asana-clone-app/ent/teammatetask"
	"asana-clone-app/ent/teammatetaskcolumn"
	"asana-clone-app/ent/teammatetaskliststatus"
	"asana-clone-app/ent/teammatetasksection"
	"asana-clone-app/ent/teammatetasktabstatus"
	"asana-clone-app/ent/workspace"
	"asana-clone-app/ent/workspaceactivity"
	"asana-clone-app/ent/workspaceteammate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceCreate is the builder for creating a Workspace entity.
type WorkspaceCreate struct {
	config
	mutation *WorkspaceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "created_by" field.
func (_c *WorkspaceCreate) SetCreatedBy(v ulid.ID) *WorkspaceCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetName sets the "name" field.
func (_c *WorkspaceCreate) SetName(v string) *WorkspaceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *WorkspaceCreate) SetDescription(v map[string]interface{}) *WorkspaceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceCreate) SetCreatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceCreate) SetUpdatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkspaceCreate) SetID(v ulid.ID) *WorkspaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableID(v *ulid.ID) *WorkspaceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTeammateID sets the "teammate" edge to the Teammate entity by ID.
func (_c *WorkspaceCreate) SetTeammateID(id ulid.ID) *WorkspaceCreate {
	_c.mutation.SetTeammateID(id)
	return _c
}

// SetTeammate sets the "teammate" edge to the Teammate entity.
func (_c *WorkspaceCreate) SetTeammate(v *Teammate) *WorkspaceCreate {
	return _c.SetTeammateID(v.ID)
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *WorkspaceCreate) AddProjectIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *WorkspaceCreate) AddProjects(v ...*Project) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// AddWorkspaceTeammateIDs adds the "workspaceTeammates" edge to the WorkspaceTeammate entity by IDs.
func (_c *WorkspaceCreate) AddWorkspaceTeammateIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddWorkspaceTeammateIDs(ids...)
	return _c
}

// AddWorkspaceTeammates adds the "workspaceTeammates" edges to the WorkspaceTeammate entity.
func (_c *WorkspaceCreate) AddWorkspaceTeammates(v ...*WorkspaceTeammate) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWorkspaceTeammateIDs(ids...)
}

// AddFavoriteWorkspaceIDs adds the "favoriteWorkspaces" edge to the FavoriteWorkspace entity by IDs.
func (_c *WorkspaceCreate) AddFavoriteWorkspaceIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddFavoriteWorkspaceIDs(ids...)
	return _c
}

// AddFavoriteWorkspaces adds the "favoriteWorkspaces" edges to the FavoriteWorkspace entity.
func (_c *WorkspaceCreate) AddFavoriteWorkspaces(v ...*FavoriteWorkspace) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFavoriteWorkspaceIDs(ids...)
}

// AddTeammateTaskTabStatuseIDs adds the "teammateTaskTabStatuses" edge to the TeammateTaskTabStatus entity by IDs.
func (_c *WorkspaceCreate) AddTeammateTaskTabStatuseIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTeammateTaskTabStatuseIDs(ids...)
	return _c
}

// AddTeammateTaskTabStatuses adds the "teammateTaskTabStatuses" edges to the TeammateTaskTabStatus entity.
func (_c *WorkspaceCreate) AddTeammateTaskTabStatuses(v ...*TeammateTaskTabStatus) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeammateTaskTabStatuseIDs(ids...)
}

// AddTeammateTaskListStatuseIDs adds the "teammateTaskListStatuses" edge to the TeammateTaskListStatus entity by IDs.
func (_c *WorkspaceCreate) AddTeammateTaskListStatuseIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTeammateTaskListStatuseIDs(ids...)
	return _c
}

// AddTeammateTaskListStatuses adds the "teammateTaskListStatuses" edges to the TeammateTaskListStatus entity.
func (_c *WorkspaceCreate) AddTeammateTaskListStatuses(v ...*TeammateTaskListStatus) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeammateTaskListStatuseIDs(ids...)
}

// AddTeammateTaskSectionIDs adds the "teammateTaskSections" edge to the TeammateTaskSection entity by IDs.
func (_c *WorkspaceCreate) AddTeammateTaskSectionIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTeammateTaskSectionIDs(ids...)
	return _c
}

// AddTeammateTaskSections adds the "teammateTaskSections" edges to the TeammateTaskSection entity.
func (_c *WorkspaceCreate) AddTeammateTaskSections(v ...*TeammateTaskSection) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeammateTaskSectionIDs(ids...)
}

// AddTaskLikeIDs adds the "taskLikes" edge to the TaskLike entity by IDs.
func (_c *WorkspaceCreate) AddTaskLikeIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTaskLikeIDs(ids...)
	return _c
}

// AddTaskLikes adds the "taskLikes" edges to the TaskLike entity.
func (_c *WorkspaceCreate) AddTaskLikes(v ...*TaskLike) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskLikeIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *WorkspaceCreate) AddTagIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *WorkspaceCreate) AddTags(v ...*Tag) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// AddTeammateTaskColumnIDs adds the "teammateTaskColumns" edge to the TeammateTaskColumn entity by IDs.
func (_c *WorkspaceCreate) AddTeammateTaskColumnIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTeammateTaskColumnIDs(ids...)
	return _c
}

// AddTeammateTaskColumns adds the "teammateTaskColumns" edges to the TeammateTaskColumn entity.
func (_c *WorkspaceCreate) AddTeammateTaskColumns(v ...*TeammateTaskColumn) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeammateTaskColumnIDs(ids...)
}

// AddTeammateTaskIDs adds the "teammateTasks" edge to the TeammateTask entity by IDs.
func (_c *WorkspaceCreate) AddTeammateTaskIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTeammateTaskIDs(ids...)
	return _c
}

// AddTeammateTasks adds the "teammateTasks" edges to the TeammateTask entity.
func (_c *WorkspaceCreate) AddTeammateTasks(v ...*TeammateTask) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeammateTaskIDs(ids...)
}

// AddDeletedTasksRefIDs adds the "deletedTasksRef" edge to the DeletedTask entity by IDs.
func (_c *WorkspaceCreate) AddDeletedTasksRefIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddDeletedTasksRefIDs(ids...)
	return _c
}

// AddDeletedTasksRef adds the "deletedTasksRef" edges to the DeletedTask entity.
func (_c *WorkspaceCreate) AddDeletedTasksRef(v ...*DeletedTask) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeletedTasksRefIDs(ids...)
}

// AddWorkspaceActivityIDs adds the "workspaceActivities" edge to the WorkspaceActivity entity by IDs.
func (_c *WorkspaceCreate) AddWorkspaceActivityIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddWorkspaceActivityIDs(ids...)
	return _c
}

// AddWorkspaceActivities adds the "workspaceActivities" edges to the WorkspaceActivity entity.
func (_c *WorkspaceCreate) AddWorkspaceActivities(v ...*WorkspaceActivity) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWorkspaceActivityIDs(ids...)
}

// AddTaskActivityIDs adds the "taskActivities" edge to the TaskActivity entity by IDs.
func (_c *WorkspaceCreate) AddTaskActivityIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddTaskActivityIDs(ids...)
	return _c
}

// AddTaskActivities adds the "taskActivities" edges to the TaskActivity entity.
func (_c *WorkspaceCreate) AddTaskActivities(v ...*TaskActivity) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskActivityIDs(ids...)
}

// AddArchivedTaskActivityIDs adds the "archivedTaskActivities" edge to the ArchivedTaskActivity entity by IDs.
func (_c *WorkspaceCreate) AddArchivedTaskActivityIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddArchivedTaskActivityIDs(ids...)
	return _c
}

// AddArchivedTaskActivities adds the "archivedTaskActivities" edges to the ArchivedTaskActivity entity.
func (_c *WorkspaceCreate) AddArchivedTaskActivities(v ...*ArchivedTaskActivity) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArchivedTaskActivityIDs(ids...)
}

// AddArchivedWorkspaceActivityIDs adds the "archivedWorkspaceActivities" edge to the ArchivedWorkspaceActivity entity by IDs.
func (_c *WorkspaceCreate) AddArchivedWorkspaceActivityIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddArchivedWorkspaceActivityIDs(ids...)
	return _c
}

// AddArchivedWorkspaceActivities adds the "archivedWorkspaceActivities" edges to the ArchivedWorkspaceActivity entity.
func (_c *WorkspaceCreate) AddArchivedWorkspaceActivities(v ...*ArchivedWorkspaceActivity) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArchivedWorkspaceActivityIDs(ids...)
}

// AddDeletedTeammateTaskIDs adds the "deletedTeammateTasks" edge to the DeletedTeammateTask entity by IDs.
func (_c *WorkspaceCreate) AddDeletedTeammateTaskIDs(ids ...ulid.ID) *WorkspaceCreate {
	_c.mutation.AddDeletedTeammateTaskIDs(ids...)
	return _c
}

// AddDeletedTeammateTasks adds the "deletedTeammateTasks" edges to the DeletedTeammateTask entity.
func (_c *WorkspaceCreate) AddDeletedTeammateTasks(v ...*DeletedTeammateTask) *WorkspaceCreate {
	ids := make([]ulid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeletedTeammateTaskIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_c *WorkspaceCreate) Mutation() *WorkspaceMutation {
	return _c.mutation
}

// Save creates the Workspace in the database.
func (_c *WorkspaceCreate) Save(ctx context.Context) (*Workspace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceCreate) SaveX(ctx context.Context) *Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspace.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := workspace.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceCreate) check() error {
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Workspace.created_by"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Workspace.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Workspace.description"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Workspace.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Workspace.updated_at"`)}
	}
	if len(_c.mutation.TeammateIDs()) == 0 {
		return &ValidationError{Name: "teammate", err: errors.New(`ent: missing required edge "Workspace.teammate"`)}
	}
	return nil
}

func (_c *WorkspaceCreate) sqlSave(ctx context.Context) (*Workspace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceCreate) createSpec() (*Workspace, *sqlgraph.CreateSpec) {
	var (
		_node = &Workspace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspace.Table, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(workspace.FieldDescription, field.TypeJSON, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TeammateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.TeammateTable,
			Columns: []string{workspace.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ProjectsTable,
			Columns: []string{workspace.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkspaceTeammatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.WorkspaceTeammatesTable,
			Columns: []string{workspace.WorkspaceTeammatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceteammate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FavoriteWorkspacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.FavoriteWorkspacesTable,
			Columns: []string{workspace.FavoriteWorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favoriteworkspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeammateTaskTabStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TeammateTaskTabStatusesTable,
			Columns: []string{workspace.TeammateTaskTabStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammatetasktabstatus.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeammateTaskListStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TeammateTaskListStatusesTable,
			Columns: []string{workspace.TeammateTaskListStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammatetaskliststatus.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeammateTaskSectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TeammateTaskSectionsTable,
			Columns: []string{workspace.TeammateTaskSectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammatetasksection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskLikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TaskLikesTable,
			Columns: []string{workspace.TaskLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasklike.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TagsTable,
			Columns: []string{workspace.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeammateTaskColumnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TeammateTaskColumnsTable,
			Columns: []string{workspace.TeammateTaskColumnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammatetaskcolumn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeammateTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TeammateTasksTable,
			Columns: []string{workspace.TeammateTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammatetask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeletedTasksRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.DeletedTasksRefTable,
			Columns: []string{workspace.DeletedTasksRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deletedtask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkspaceActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.WorkspaceActivitiesTable,
			Columns: []string{workspace.WorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TaskActivitiesTable,
			Columns: []string{workspace.TaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ArchivedTaskActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ArchivedTaskActivitiesTable,
			Columns: []string{workspace.ArchivedTaskActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedtaskactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ArchivedWorkspaceActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ArchivedWorkspaceActivitiesTable,
			Columns: []string{workspace.ArchivedWorkspaceActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archivedworkspaceactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeletedTeammateTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.DeletedTeammateTasksTable,
			Columns: []string{workspace.DeletedTeammateTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deletedteammatetask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Workspace.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceCreate) OnConflict(opts ...sql.ConflictOption) *WorkspaceUpsertOne {
	_c.conflict = opts
	return &WorkspaceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceCreate) OnConflictColumns(columns ...string) *WorkspaceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceUpsertOne{
		create: _c,
	}
}

type (
	// WorkspaceUpsertOne is the builder for "upsert"-ing
	//  one Workspace node.
	WorkspaceUpsertOne struct {
		create *WorkspaceCreate
	}

	// WorkspaceUpsert is the "OnConflict" setter.
	WorkspaceUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedBy sets the "created_by" field.
func (u *WorkspaceUpsert) SetCreatedBy(v ulid.ID) *WorkspaceUpsert {
	u.Set(workspace.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateCreatedBy() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldCreatedBy)
	return u
}

// SetName sets the "name" field.
func (u *WorkspaceUpsert) SetName(v string) *WorkspaceUpsert {
	u.Set(workspace.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateName() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *WorkspaceUpsert) SetDescription(v map[string]interface{}) *WorkspaceUpsert {
	u.Set(workspace.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateDescription() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldDescription)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceUpsert) SetUpdatedAt(v time.Time) *WorkspaceUpsert {
	u.Set(workspace.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateUpdatedAt() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workspace.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkspaceUpsertOne) UpdateNewValues() *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(workspace.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(workspace.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Workspace.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkspaceUpsertOne) Ignore() *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceUpsertOne) DoNothing() *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceCreate.OnConflict
// documentation for more info.
func (u *WorkspaceUpsertOne) Update(set func(*WorkspaceUpsert)) *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *WorkspaceUpsertOne) SetCreatedBy(v ulid.ID) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateCreatedBy() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetName sets the "name" field.
func (u *WorkspaceUpsertOne) SetName(v string) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateName() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *WorkspaceUpsertOne) SetDescription(v map[string]interface{}) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateDescription() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateDescription()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceUpsertOne) SetUpdatedAt(v time.Time) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateUpdatedAt() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkspaceUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WorkspaceUpsertOne.ID is not supported by MySQL driver. Use WorkspaceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkspaceUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkspaceCreateBulk is the builder for creating many Workspace entities in bulk.
type WorkspaceCreateBulk struct {
	config
	err      error
	builders []*WorkspaceCreate
	conflict []sql.ConflictOption
}

// Save creates the Workspace entities in the database.
func (_c *WorkspaceCreateBulk) Save(ctx context.Context) ([]*Workspace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Workspace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) SaveX(ctx context.Context) []*Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Workspace.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkspaceUpsertBulk {
	_c.conflict = opts
	return &WorkspaceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceCreateBulk) OnConflictColumns(columns ...string) *WorkspaceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceUpsertBulk{
		create: _c,
	}
}

// WorkspaceUpsertBulk is the builder for "upsert"-ing
// a bulk of Workspace nodes.
type WorkspaceUpsertBulk struct {
	create *WorkspaceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workspace.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkspaceUpsertBulk) UpdateNewValues() *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(workspace.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(workspace.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkspaceUpsertBulk) Ignore() *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceUpsertBulk) DoNothing() *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceCreateBulk.OnConflict
// documentation for more info.
func (u *WorkspaceUpsertBulk) Update(set func(*WorkspaceUpsert)) *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *WorkspaceUpsertBulk) SetCreatedBy(v ulid.ID) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateCreatedBy() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetName sets the "name" field.
func (u *WorkspaceUpsertBulk) SetName(v string) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateName() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *WorkspaceUpsertBulk) SetDescription(v map[string]interface{}) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateDescription() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateDescription()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceUpsertBulk) SetUpdatedAt(v time.Time) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateUpdatedAt() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkspaceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
