// Code generated by ent, DO NOT EDIT.

package archivedtaskactivity

import (
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLTE(FieldID, id))
}

// ActivityTypeID applies equality check predicate on the "activity_type_id" field. It's identical to ActivityTypeIDEQ.
func ActivityTypeID(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldActivityTypeID, v))
}

// TeammateID applies equality check predicate on the "teammate_id" field. It's identical to TeammateIDEQ.
func TeammateID(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldTeammateID, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldWorkspaceID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// ActivityTypeIDEQ applies the EQ predicate on the "activity_type_id" field.
func ActivityTypeIDEQ(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldActivityTypeID, v))
}

// ActivityTypeIDNEQ applies the NEQ predicate on the "activity_type_id" field.
func ActivityTypeIDNEQ(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNEQ(FieldActivityTypeID, v))
}

// ActivityTypeIDIn applies the In predicate on the "activity_type_id" field.
func ActivityTypeIDIn(vs ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldIn(FieldActivityTypeID, vs...))
}

// ActivityTypeIDNotIn applies the NotIn predicate on the "activity_type_id" field.
func ActivityTypeIDNotIn(vs ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNotIn(FieldActivityTypeID, vs...))
}

// ActivityTypeIDGT applies the GT predicate on the "activity_type_id" field.
func ActivityTypeIDGT(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGT(FieldActivityTypeID, v))
}

// ActivityTypeIDGTE applies the GTE predicate on the "activity_type_id" field.
func ActivityTypeIDGTE(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGTE(FieldActivityTypeID, v))
}

// ActivityTypeIDLT applies the LT predicate on the "activity_type_id" field.
func ActivityTypeIDLT(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLT(FieldActivityTypeID, v))
}

// ActivityTypeIDLTE applies the LTE predicate on the "activity_type_id" field.
func ActivityTypeIDLTE(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLTE(FieldActivityTypeID, v))
}

// ActivityTypeIDContains applies the Contains predicate on the "activity_type_id" field.
func ActivityTypeIDContains(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldContains(FieldActivityTypeID, vc))
}

// ActivityTypeIDHasPrefix applies the HasPrefix predicate on the "activity_type_id" field.
func ActivityTypeIDHasPrefix(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldHasPrefix(FieldActivityTypeID, vc))
}

// ActivityTypeIDHasSuffix applies the HasSuffix predicate on the "activity_type_id" field.
func ActivityTypeIDHasSuffix(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldHasSuffix(FieldActivityTypeID, vc))
}

// ActivityTypeIDEqualFold applies the EqualFold predicate on the "activity_type_id" field.
func ActivityTypeIDEqualFold(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldEqualFold(FieldActivityTypeID, vc))
}

// ActivityTypeIDContainsFold applies the ContainsFold predicate on the "activity_type_id" field.
func ActivityTypeIDContainsFold(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldContainsFold(FieldActivityTypeID, vc))
}

// TeammateIDEQ applies the EQ predicate on the "teammate_id" field.
func TeammateIDEQ(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldTeammateID, v))
}

// TeammateIDNEQ applies the NEQ predicate on the "teammate_id" field.
func TeammateIDNEQ(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNEQ(FieldTeammateID, v))
}

// TeammateIDIn applies the In predicate on the "teammate_id" field.
func TeammateIDIn(vs ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldIn(FieldTeammateID, vs...))
}

// TeammateIDNotIn applies the NotIn predicate on the "teammate_id" field.
func TeammateIDNotIn(vs ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNotIn(FieldTeammateID, vs...))
}

// TeammateIDGT applies the GT predicate on the "teammate_id" field.
func TeammateIDGT(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGT(FieldTeammateID, v))
}

// TeammateIDGTE applies the GTE predicate on the "teammate_id" field.
func TeammateIDGTE(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGTE(FieldTeammateID, v))
}

// TeammateIDLT applies the LT predicate on the "teammate_id" field.
func TeammateIDLT(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLT(FieldTeammateID, v))
}

// TeammateIDLTE applies the LTE predicate on the "teammate_id" field.
func TeammateIDLTE(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLTE(FieldTeammateID, v))
}

// TeammateIDContains applies the Contains predicate on the "teammate_id" field.
func TeammateIDContains(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldContains(FieldTeammateID, vc))
}

// TeammateIDHasPrefix applies the HasPrefix predicate on the "teammate_id" field.
func TeammateIDHasPrefix(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldHasPrefix(FieldTeammateID, vc))
}

// TeammateIDHasSuffix applies the HasSuffix predicate on the "teammate_id" field.
func TeammateIDHasSuffix(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldHasSuffix(FieldTeammateID, vc))
}

// TeammateIDEqualFold applies the EqualFold predicate on the "teammate_id" field.
func TeammateIDEqualFold(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldEqualFold(FieldTeammateID, vc))
}

// TeammateIDContainsFold applies the ContainsFold predicate on the "teammate_id" field.
func TeammateIDContainsFold(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldContainsFold(FieldTeammateID, vc))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v ulid.ID) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLTE(FieldWorkspaceID, v))
}

// WorkspaceIDContains applies the Contains predicate on the "workspace_id" field.
func WorkspaceIDContains(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldContains(FieldWorkspaceID, vc))
}

// WorkspaceIDHasPrefix applies the HasPrefix predicate on the "workspace_id" field.
func WorkspaceIDHasPrefix(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldHasPrefix(FieldWorkspaceID, vc))
}

// WorkspaceIDHasSuffix applies the HasSuffix predicate on the "workspace_id" field.
func WorkspaceIDHasSuffix(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldHasSuffix(FieldWorkspaceID, vc))
}

// WorkspaceIDEqualFold applies the EqualFold predicate on the "workspace_id" field.
func WorkspaceIDEqualFold(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldEqualFold(FieldWorkspaceID, vc))
}

// WorkspaceIDContainsFold applies the ContainsFold predicate on the "workspace_id" field.
func WorkspaceIDContainsFold(v ulid.ID) predicate.ArchivedTaskActivity {
	vc := string(v)
	return predicate.ArchivedTaskActivity(sql.FieldContainsFold(FieldWorkspaceID, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTeammate applies the HasEdge predicate on the "teammate" edge.
func HasTeammate() predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeammateTable, TeammateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeammateWith applies the HasEdge predicate on the "teammate" edge with a given conditions (other predicates).
func HasTeammateWith(preds ...predicate.Teammate) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := newTeammateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActivityType applies the HasEdge predicate on the "activityType" edge.
func HasActivityType() predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTypeTable, ActivityTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivityTypeWith applies the HasEdge predicate on the "activityType" edge with a given conditions (other predicates).
func HasActivityTypeWith(preds ...predicate.ActivityType) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := newActivityTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasArchivedTaskActivityTasks applies the HasEdge predicate on the "archivedTaskActivityTasks" edge.
func HasArchivedTaskActivityTasks() predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArchivedTaskActivityTasksTable, ArchivedTaskActivityTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArchivedTaskActivityTasksWith applies the HasEdge predicate on the "archivedTaskActivityTasks" edge with a given conditions (other predicates).
func HasArchivedTaskActivityTasksWith(preds ...predicate.ArchivedTaskActivityTask) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(func(s *sql.Selector) {
		step := newArchivedTaskActivityTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ArchivedTaskActivity) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ArchivedTaskActivity) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ArchivedTaskActivity) predicate.ArchivedTaskActivity {
	return predicate.ArchivedTaskActivity(sql.NotPredicates(p))
}
