// Code generated by ent, DO NOT EDIT.

package workspaceteammate

import (
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLTE(FieldID, id))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldWorkspaceID, v))
}

// TeammateID applies equality check predicate on the "teammate_id" field. It's identical to TeammateIDEQ.
func TeammateID(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldTeammateID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldRole, v))
}

// IsOwner applies equality check predicate on the "is_owner" field. It's identical to IsOwnerEQ.
func IsOwner(v bool) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldIsOwner, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLTE(FieldWorkspaceID, v))
}

// WorkspaceIDContains applies the Contains predicate on the "workspace_id" field.
func WorkspaceIDContains(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldContains(FieldWorkspaceID, vc))
}

// WorkspaceIDHasPrefix applies the HasPrefix predicate on the "workspace_id" field.
func WorkspaceIDHasPrefix(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldHasPrefix(FieldWorkspaceID, vc))
}

// WorkspaceIDHasSuffix applies the HasSuffix predicate on the "workspace_id" field.
func WorkspaceIDHasSuffix(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldHasSuffix(FieldWorkspaceID, vc))
}

// WorkspaceIDEqualFold applies the EqualFold predicate on the "workspace_id" field.
func WorkspaceIDEqualFold(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldEqualFold(FieldWorkspaceID, vc))
}

// WorkspaceIDContainsFold applies the ContainsFold predicate on the "workspace_id" field.
func WorkspaceIDContainsFold(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldContainsFold(FieldWorkspaceID, vc))
}

// TeammateIDEQ applies the EQ predicate on the "teammate_id" field.
func TeammateIDEQ(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldTeammateID, v))
}

// TeammateIDNEQ applies the NEQ predicate on the "teammate_id" field.
func TeammateIDNEQ(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldTeammateID, v))
}

// TeammateIDIn applies the In predicate on the "teammate_id" field.
func TeammateIDIn(vs ...ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldIn(FieldTeammateID, vs...))
}

// TeammateIDNotIn applies the NotIn predicate on the "teammate_id" field.
func TeammateIDNotIn(vs ...ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNotIn(FieldTeammateID, vs...))
}

// TeammateIDGT applies the GT predicate on the "teammate_id" field.
func TeammateIDGT(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGT(FieldTeammateID, v))
}

// TeammateIDGTE applies the GTE predicate on the "teammate_id" field.
func TeammateIDGTE(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGTE(FieldTeammateID, v))
}

// TeammateIDLT applies the LT predicate on the "teammate_id" field.
func TeammateIDLT(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLT(FieldTeammateID, v))
}

// TeammateIDLTE applies the LTE predicate on the "teammate_id" field.
func TeammateIDLTE(v ulid.ID) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLTE(FieldTeammateID, v))
}

// TeammateIDContains applies the Contains predicate on the "teammate_id" field.
func TeammateIDContains(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldContains(FieldTeammateID, vc))
}

// TeammateIDHasPrefix applies the HasPrefix predicate on the "teammate_id" field.
func TeammateIDHasPrefix(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldHasPrefix(FieldTeammateID, vc))
}

// TeammateIDHasSuffix applies the HasSuffix predicate on the "teammate_id" field.
func TeammateIDHasSuffix(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldHasSuffix(FieldTeammateID, vc))
}

// TeammateIDEqualFold applies the EqualFold predicate on the "teammate_id" field.
func TeammateIDEqualFold(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldEqualFold(FieldTeammateID, vc))
}

// TeammateIDContainsFold applies the ContainsFold predicate on the "teammate_id" field.
func TeammateIDContainsFold(v ulid.ID) predicate.WorkspaceTeammate {
	vc := string(v)
	return predicate.WorkspaceTeammate(sql.FieldContainsFold(FieldTeammateID, vc))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldContainsFold(FieldRole, v))
}

// IsOwnerEQ applies the EQ predicate on the "is_owner" field.
func IsOwnerEQ(v bool) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldIsOwner, v))
}

// IsOwnerNEQ applies the NEQ predicate on the "is_owner" field.
func IsOwnerNEQ(v bool) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldIsOwner, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeammate applies the HasEdge predicate on the "teammate" edge.
func HasTeammate() predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeammateTable, TeammateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeammateWith applies the HasEdge predicate on the "teammate" edge with a given conditions (other predicates).
func HasTeammateWith(preds ...predicate.Teammate) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(func(s *sql.Selector) {
		step := newTeammateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkspaceTeammate) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkspaceTeammate) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkspaceTeammate) predicate.WorkspaceTeammate {
	return predicate.WorkspaceTeammate(sql.NotPredicates(p))
}
