package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"asana-clone-app/ent"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/graph/generated"
	"asana-clone-app/pkg/adapter/handler"
	"asana-clone-app/pkg/util/datetime"
	"context"

	"entgo.io/contrib/entgql"
)

// CreateTaskListSortStatus is the resolver for the createTaskListSortStatus field.
func (r *mutationResolver) CreateTaskListSortStatus(ctx context.Context, input ent.CreateTaskListSortStatusInput) (*ent.TaskListSortStatus, error) {
	t, err := r.controller.TaskListSortStatus.Create(ctx, input)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}
	return t, nil
}

// UpdateTaskListSortStatus is the resolver for the updateTaskListSortStatus field.
func (r *mutationResolver) UpdateTaskListSortStatus(ctx context.Context, input ent.UpdateTaskListSortStatusInput) (*ent.TaskListSortStatus, error) {
	t, err := r.controller.TaskListSortStatus.Update(ctx, input)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}
	return t, nil
}

// TaskListSortStatus is the resolver for the taskListSortStatus field.
func (r *queryResolver) TaskListSortStatus(ctx context.Context, where *ent.TaskListSortStatusWhereInput) (*ent.TaskListSortStatus, error) {
	t, err := r.controller.TaskListSortStatus.Get(ctx, where)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}
	return t, nil
}

// TaskListSortStatuses is the resolver for the taskListSortStatuses field.
func (r *queryResolver) TaskListSortStatuses(ctx context.Context, after *entgql.Cursor[ulid.ID], first *int, before *entgql.Cursor[ulid.ID], last *int, where *ent.TaskListSortStatusWhereInput) (*ent.TaskListSortStatusConnection, error) {
	ts, err := r.controller.TaskListSortStatus.ListWithPagination(ctx, after, first, before, last, where)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}
	return ts, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *taskListSortStatusResolver) CreatedAt(ctx context.Context, obj *ent.TaskListSortStatus) (string, error) {
	return datetime.FormatDate(obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *taskListSortStatusResolver) UpdatedAt(ctx context.Context, obj *ent.TaskListSortStatus) (string, error) {
	return datetime.FormatDate(obj.UpdatedAt), nil
}

// TaskListSortStatus returns generated.TaskListSortStatusResolver implementation.
func (r *Resolver) TaskListSortStatus() generated.TaskListSortStatusResolver {
	return &taskListSortStatusResolver{r}
}

type taskListSortStatusResolver struct{ *Resolver }
