package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"asana-clone-app/ent"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/graph/generated"
	"asana-clone-app/pkg/adapter/handler"
	"asana-clone-app/pkg/entity/model"
	"asana-clone-app/pkg/util/datetime"
	"asana-clone-app/pkg/util/subscription"
	"context"

	"entgo.io/contrib/entgql"
)

// CreateTaskTag is the resolver for the createTaskTag field.
func (r *mutationResolver) CreateTaskTag(ctx context.Context, input ent.CreateTaskTagInput) (*ent.TaskTag, error) {
	t, err := r.controller.TaskTag.Create(ctx, input)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}

	go func() {
		for _, c := range r.subscriptions.TaskTagCreated {
			if c.WorkspaceID == input.WorkspaceID && c.RequestID != input.RequestID {
				c.Ch <- t
			}
		}
	}()

	return t, nil
}

// UpdateTaskTag is the resolver for the updateTaskTag field.
func (r *mutationResolver) UpdateTaskTag(ctx context.Context, input ent.UpdateTaskTagInput) (*ent.TaskTag, error) {
	t, err := r.controller.TaskTag.Update(ctx, input)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}

	return t, nil
}

// DeleteTaskTag is the resolver for the deleteTaskTag field.
func (r *mutationResolver) DeleteTaskTag(ctx context.Context, input model.DeleteTaskTagInput) (*ent.TaskTag, error) {
	t, err := r.controller.TaskTag.Delete(ctx, input)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}

	go func() {
		for _, d := range r.subscriptions.TaskTagDeleted {
			if d.WorkspaceID == input.WorkspaceID && d.RequestID != input.RequestID {
				d.Ch <- t
			}
		}
	}()

	return t, nil
}

// TaskTag is the resolver for the taskTag field.
func (r *queryResolver) TaskTag(ctx context.Context, where *ent.TaskTagWhereInput) (*ent.TaskTag, error) {
	t, err := r.controller.TaskTag.Get(ctx, where)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}

	return t, nil
}

// TaskTags is the resolver for the taskTags field.
func (r *queryResolver) TaskTags(ctx context.Context, after *entgql.Cursor[ulid.ID], first *int, before *entgql.Cursor[ulid.ID], last *int, where *ent.TaskTagWhereInput) (*ent.TaskTagConnection, error) {
	ts, err := r.controller.TaskTag.ListWithPagination(ctx, after, first, before, last, where)
	if err != nil {
		return nil, handler.HandleGraphQLError(ctx, err)
	}

	return ts, nil
}

// TaskTagsUpdated is the resolver for the taskTagsUpdated field.
func (r *subscriptionResolver) TaskTagsUpdated(ctx context.Context, taskID ulid.ID, requestID string) (<-chan []*ent.TaskTag, error) {
	key := subscription.NewKey()
	ch := make(chan []*ent.TaskTag, 1)

	r.mutex.Lock()
	r.subscriptions.TaskTagUpdated[key] = subscription.TaskTagUpdated{
		TaskID:    taskID,
		RequestID: requestID,
		Ch:        ch,
	}
	r.mutex.Unlock()

	go func() {
		<-ctx.Done()
		r.mutex.Lock()
		delete(r.subscriptions.TaskTagUpdated, key)
		r.mutex.Unlock()
	}()

	return ch, nil
}

// TaskTagCreated is the resolver for the taskTagCreated field.
func (r *subscriptionResolver) TaskTagCreated(ctx context.Context, workspaceID ulid.ID, requestID string) (<-chan *ent.TaskTag, error) {
	key := subscription.NewKey()
	ch := make(chan *ent.TaskTag, 1)

	r.mutex.Lock()
	r.subscriptions.TaskTagCreated[key] = subscription.TaskTagCreated{
		WorkspaceID: workspaceID,
		RequestID:   requestID,
		Ch:          ch,
	}
	r.mutex.Unlock()

	go func() {
		<-ctx.Done()
		r.mutex.Lock()
		delete(r.subscriptions.TaskTagCreated, key)
		r.mutex.Unlock()
	}()

	return ch, nil
}

// TaskTagDeleted is the resolver for the taskTagDeleted field.
func (r *subscriptionResolver) TaskTagDeleted(ctx context.Context, workspaceID ulid.ID, requestID string) (<-chan *ent.TaskTag, error) {
	key := subscription.NewKey()
	ch := make(chan *ent.TaskTag, 1)

	r.mutex.Lock()
	r.subscriptions.TaskTagDeleted[key] = subscription.TaskTagDeleted{
		WorkspaceID: workspaceID,
		RequestID:   requestID,
		Ch:          ch,
	}
	r.mutex.Unlock()

	go func() {
		<-ctx.Done()
		r.mutex.Lock()
		delete(r.subscriptions.TaskTagDeleted, key)
		r.mutex.Unlock()
	}()

	return ch, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *taskTagResolver) CreatedAt(ctx context.Context, obj *ent.TaskTag) (string, error) {
	return datetime.FormatDate(obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *taskTagResolver) UpdatedAt(ctx context.Context, obj *ent.TaskTag) (string, error) {
	return datetime.FormatDate(obj.UpdatedAt), nil
}

// TaskTag returns generated.TaskTagResolver implementation.
func (r *Resolver) TaskTag() generated.TaskTagResolver { return &taskTagResolver{r} }

type taskTagResolver struct{ *Resolver }
