// Code generated by ent, DO NOT EDIT.

package projecttaskcolumn

import (
	"project-management-demo-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the projecttaskcolumn type in the database.
	Label = "project_task_column"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTaskColumnID holds the string denoting the task_column_id field in the database.
	FieldTaskColumnID = "task_column_id"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldCustomizable holds the string denoting the customizable field in the database.
	FieldCustomizable = "customizable"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeTaskColumn holds the string denoting the taskcolumn edge name in mutations.
	EdgeTaskColumn = "taskColumn"
	// Table holds the table name of the projecttaskcolumn in the database.
	Table = "project_task_columns"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_task_columns"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// TaskColumnTable is the table that holds the taskColumn relation/edge.
	TaskColumnTable = "project_task_columns"
	// TaskColumnInverseTable is the table name for the TaskColumn entity.
	// It exists in this package in order to avoid circular dependency with the "taskcolumn" package.
	TaskColumnInverseTable = "task_columns"
	// TaskColumnColumn is the table column denoting the taskColumn relation/edge.
	TaskColumnColumn = "task_column_id"
)

// Columns holds all SQL columns for projecttaskcolumn fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldTaskColumnID,
	FieldWidth,
	FieldDisabled,
	FieldCustomizable,
	FieldOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// WidthValidator is a validator for the "width" field. It is called by the builders before save.
	WidthValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)

// OrderOption defines the ordering options for the ProjectTaskColumn queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByTaskColumnID orders the results by the task_column_id field.
func ByTaskColumnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskColumnID, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByCustomizable orders the results by the customizable field.
func ByCustomizable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomizable, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByTaskColumnField orders the results by taskColumn field.
func ByTaskColumnField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskColumnStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newTaskColumnStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskColumnInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaskColumnTable, TaskColumnColumn),
	)
}
