// Generated by `yarn new:queryMock`
import { server } from '../../server';
import { projectTeammatesQuery } from '../project-teammates';
import type { Options } from './type';

export const setProjectTeammatesQuery = (options: Options) => {
  server.use(projectTeammatesQuery(options));
};
