name: 【nextjs】Chromatic main
on:
  push:
    branches: [main]
    paths:
      - "apps/nextjs/**"
      - ".github/workflows/nextjs-chromatic-main.yml"

jobs:
  chromatic:
    name: chromatic main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup monorepo
        uses: ./.github/actions/setup
      - name: Run codegen
        run: pnpm --filter nextjs codegen:ci
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
          workingDir: apps/nextjs
