name: 【nextjs】 CI
on:
  pull_request:
    branches: [main]
    paths:
      - "apps/nextjs/**"
      - ".github/workflows/nextjs-ci.yml"

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    env:
      SAFE_CHAIN_LOGGING: silent
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup monorepo
        uses: ./.github/actions/setup
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright_cache_id
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright browsers
        if: steps.playwright_cache_id.outputs.cache-hit != 'true'
        run: pnpm --filter nextjs exec playwright install --with-deps chromium
      - name: Install Playwright system dependencies
        if: steps.playwright_cache_id.outputs.cache-hit == 'true'
        run: pnpm --filter nextjs exec playwright install-deps chromium
      - name: Run codegen
        run: pnpm --filter nextjs codegen:ci
      - name: Run lint
        run: pnpm --filter nextjs lint
      - name: Run test
        run: pnpm --filter nextjs test:ci
